export type LangCode =
  | "de" | "vi" | "en" | "fr" | "es" | "it" | "pt" | "pl"
  | "ru" | "tr" | "ar" | "zh" | "ja" | "ko" | "nl" | "ro"
  | "hu" | "cs" | "el" | "hi" | "uk";

export interface Translations {
  langName: string;
  flag: string;
  dir: "ltr" | "rtl";
  nav: {
    home: string; menu: string; order: string; about: string; contact: string; careers: string;
  };
  common: {
    orderNow: string; viewMenu: string; viewFullMenu: string; learnMore: string;
    phone: string; address: string; openingHours: string; closed: string;
    monday: string; saturday: string; sunday: string;
  };
  home: {
    heroDesc: string;
    categoriesTitle: string;
    noodleBox: string; noodleBoxDesc: string;
    curry: string; curryDesc: string;
    springRolls: string; springRollsDesc: string;
    freshTitle: string; freshDesc: string;
    testimonialsTitle: string;
    testimonialQuote: string; testimonialAuthor: string;
    ctaTitle: string; ctaDesc: string; ctaBtn: string;
  };
  menu: { title: string; subtitle: string; };
  order: {
    title: string; subtitle: string; phoneDirect: string;
    cartTitle: string; cartEmpty: string; cartEmptyHint: string;
    total: string; checkout: string; phoneAlt: string;
    small: string; large: string; addToCart: string;
    sauceNote: string;
  };
  about: {
    title: string; subtitle: string;
    storyTag: string; whoTag: string; whoTitle: string; whoDesc: string;
    drivesTag: string; drivesTitle: string;
    valueHeart: string; valueHeartDesc: string;
    valueFresh: string; valueFreshDesc: string;
    valueFamily: string; valueFamilyDesc: string;
    valueLocal: string; valueLocalDesc: string;
    hoursTag: string; hoursTitle: string;
    addressTag: string; addressTitle: string;
    mondayFriday: string; saturdayHours: string; sundayClosed: string;
  };
  contact: {
    title: string; subtitle: string; reachTitle: string;
    phoneLabel: string; phoneHint: string;
    addressLabel: string; hoursLabel: string; hoursMoSa: string; hoursSun: string;
    mapsBtn: string; msgTitle: string;
    thankYouTitle: string; thankYouDesc: string;
    nameLabel: string; namePlaceholder: string;
    emailLabel: string; emailPlaceholder: string;
    msgLabel: string; msgPlaceholder: string;
    sendBtn: string;
  };
  careers: {
    title: string; subtitle: string;
  };
  checkout: {
    title: string; backToOrder: string;
    yourDetails: string; nameLabel: string; phoneLabelReq: string;
    emailLabel: string; notesLabel: string; notesPlaceholder: string;
    pickupOrDelivery: string; pickup: string; delivery: string;
    streetPlaceholder: string; zipPlaceholder: string; cityPlaceholder: string;
    payment: string; continueBtn: string; editDetails: string;
    securePayment: string; orderSummary: string; subtotal: string;
    deliveryFee: string; total: string; sslNote: string;
    thankYou: string; thankYouMsg: string; thankYouPhone: string; backHome: string;
    cartEmpty: string; cartEmptyLink: string; loading: string;
  };
  footer: {
    tagline: string; rights: string;
  };
}

const t: Record<LangCode, Translations> = {
  de: {
    langName: "Deutsch", flag: "🇩🇪", dir: "ltr",
    nav: { home: "Home", menu: "Menü", order: "Bestellen", about: "Über uns", contact: "Kontakt", careers: "Bewerben" },
    common: { orderNow: "Jetzt bestellen", viewMenu: "Zum Menü", viewFullMenu: "Vollständiges Menü", learnMore: "Mehr erfahren", phone: "Telefon", address: "Adresse", openingHours: "Öffnungszeiten", closed: "Geschlossen", monday: "Montag", saturday: "Samstag", sunday: "Sonntag" },
    home: { heroDesc: "Authentische asiatische Küche — von knusprigen Frühlingsrollen über gebratenen Reis bis zu aromatischen Thai-Curries. Frisch zubereitet, mit Liebe serviert.", categoriesTitle: "Was uns besonders macht", noodleBox: "Noodle Box", noodleBoxDesc: "Gebratene Nudeln oder Reis, frisch zubereitet", curry: "Thai Curry", curryDesc: "Cremige Kokosmilch, frische Kräuter", springRolls: "Frühlingsrollen", springRollsDesc: "Knusprig frittiert, hausgemachte Soße", freshTitle: "Frische Zutaten, täglich zubereitet", freshDesc: "Wir verarbeiten täglich frisches Gemüse, hochwertiges Fleisch und ausgesuchte Gewürze — kein Kompromiss bei der Qualität.", testimonialsTitle: "Was unsere Gäste sagen", testimonialQuote: "\"Das beste asiatische Restaurant in Schwäbisch Gmünd! Die Noodle Box ist einfach unschlagbar — frisch, würzig und immer perfekt.\"", testimonialAuthor: "— Maria S., treue Stammkundin", ctaTitle: "Hunger auf Asien?", ctaDesc: "Bestellen Sie jetzt online oder besuchen Sie uns direkt in der Ledergasse 44–46.", ctaBtn: "Online bestellen" },
    menu: { title: "Speisekarte", subtitle: "Frisch zubereitet — jeden Tag." },
    order: { title: "Bestellen", subtitle: "Wählen Sie Ihre Gerichte und wir melden uns telefonisch zur Bestätigung.", phoneDirect: "Direkt anrufen:", cartTitle: "Warenkorb", cartEmpty: "Noch nichts im Warenkorb", cartEmptyHint: "Wählen Sie Gerichte aus", total: "Gesamt", checkout: "Zur Kasse", phoneAlt: "Lieber telefonisch bestellen?", small: "Klein", large: "Groß", addToCart: "Hinzufügen", sauceNote: "Inkl. Soße: Sojasoße, Süßsauersoße oder Thaicurry mit Kokosmilch" },
    about: { title: "Über uns", subtitle: "Authentische asiatische Küche mitten in Schwäbisch Gmünd.", storyTag: "Unsere Geschichte", whoTag: "Wer wir sind", whoTitle: "Mit Leidenschaft für Geschmack", whoDesc: "LYS Noodle Box steht für authentische asiatische Küche mit Herz. Was als kleine Familienküche begann, ist heute ein fester Bestandteil der Gmünder Gastronomieszene.", drivesTag: "Was uns antreibt", drivesTitle: "Was uns antreibt", valueHeart: "Mit Herz", valueHeartDesc: "Jedes Gericht wird mit echter Leidenschaft und Sorgfalt zubereitet — kein Fast Food, sondern echte Küche.", valueFresh: "Frische Zutaten", valueFreshDesc: "Wir setzen auf frische, qualitativ hochwertige Zutaten — täglich und ohne Kompromisse.", valueFamily: "Familiär", valueFamilyDesc: "Als Familienbetrieb stehen Wärme und persönliche Gastfreundschaft an erster Stelle.", valueLocal: "Regional verankert", valueLocalDesc: "Mitten in Schwäbisch Gmünd — Ihr Nachbar für asiatische Spezialitäten seit Jahren.", hoursTag: "Immer für Sie da", hoursTitle: "Öffnungszeiten", addressTag: "Finden Sie uns", addressTitle: "Adresse", mondayFriday: "Montag – Freitag", saturdayHours: "Samstag", sundayClosed: "Geschlossen" },
    contact: { title: "Kontakt", subtitle: "Schreiben Sie uns", reachTitle: "So erreichen Sie uns", phoneLabel: "Telefon", phoneHint: "Am schnellsten erreichen Sie uns per Telefon", addressLabel: "Adresse", hoursLabel: "Öffnungszeiten", hoursMoSa: "Mo–Sa: 11:00–20:30 Uhr", hoursSun: "Sonntag geschlossen", mapsBtn: "In Google Maps öffnen", msgTitle: "Nachricht schreiben", thankYouTitle: "Danke für Ihre Nachricht!", thankYouDesc: "Wir melden uns so schnell wie möglich bei Ihnen.", nameLabel: "Name", namePlaceholder: "Max Mustermann", emailLabel: "E-Mail", emailPlaceholder: "ihre@email.de", msgLabel: "Nachricht", msgPlaceholder: "Wie können wir Ihnen helfen?", sendBtn: "Nachricht senden" },
    careers: { title: "Bewerben", subtitle: "Werden Sie Teil unseres Teams" },
    checkout: { title: "Kasse", backToOrder: "Zurück zur Bestellung", yourDetails: "Ihre Daten", nameLabel: "Name *", phoneLabelReq: "Telefon *", emailLabel: "E-Mail", notesLabel: "Anmerkungen zur Bestellung", notesPlaceholder: "z.B. ohne Schärfe, extra Soße …", pickupOrDelivery: "Abholung oder Lieferung", pickup: "🏪 Abholung", delivery: "🛵 Lieferung (+2,00 €)", streetPlaceholder: "Straße und Hausnummer", zipPlaceholder: "PLZ", cityPlaceholder: "Ort", payment: "Zahlung", continueBtn: "Weiter zur Zahlung", editDetails: "Angaben bearbeiten", securePayment: "Sichere Zahlung", orderSummary: "Bestellung", subtotal: "Zwischensumme", deliveryFee: "Liefergebühr", total: "Gesamt", sslNote: "SSL-verschlüsselte Zahlung", thankYou: "Vielen Dank!", thankYouMsg: "Ihre Bestellung wurde erfolgreich aufgegeben", thankYouPhone: "Wir melden uns per Telefon zur Bestätigung.", backHome: "Zurück zur Startseite", cartEmpty: "Ihr Warenkorb ist leer.", cartEmptyLink: "Zurück zur Bestellung", loading: "Wird geladen…" },
    footer: { tagline: "Authentische asiatische Küche in Schwäbisch Gmünd.", rights: "Alle Rechte vorbehalten." },
  },

  vi: {
    langName: "Tiếng Việt", flag: "🇻🇳", dir: "ltr",
    nav: { home: "Trang chủ", menu: "Thực đơn", order: "Đặt món", about: "Về chúng tôi", contact: "Liên hệ", careers: "Tuyển dụng" },
    common: { orderNow: "Đặt hàng ngay", viewMenu: "Xem thực đơn", viewFullMenu: "Thực đơn đầy đủ", learnMore: "Tìm hiểu thêm", phone: "Điện thoại", address: "Địa chỉ", openingHours: "Giờ mở cửa", closed: "Đóng cửa", monday: "Thứ Hai", saturday: "Thứ Bảy", sunday: "Chủ Nhật" },
    home: { heroDesc: "Ẩm thực châu Á chính thống — từ chả giò giòn rụm, cơm rang đến cà ri Thái thơm ngon. Chế biến tươi mỗi ngày, phục vụ với tất cả tình yêu.", categoriesTitle: "Điều làm chúng tôi đặc biệt", noodleBox: "Hộp Mỳ", noodleBoxDesc: "Mỳ hoặc cơm xào, chế biến tươi mỗi ngày", curry: "Cà ri Thái", curryDesc: "Nước cốt dừa béo ngậy, thảo mộc tươi", springRolls: "Chả giò", springRollsDesc: "Chiên giòn, sốt tự làm", freshTitle: "Nguyên liệu tươi, chế biến mỗi ngày", freshDesc: "Chúng tôi dùng rau củ tươi, thịt chất lượng cao và gia vị tuyển chọn mỗi ngày — không thỏa hiệp về chất lượng.", testimonialsTitle: "Khách hàng nói gì", testimonialQuote: "\"Nhà hàng châu Á ngon nhất Schwäbisch Gmünd! Hộp mỳ thật tuyệt — tươi, đậm vị và luôn hoàn hảo.\"", testimonialAuthor: "— Maria S., khách hàng thân thiết", ctaTitle: "Thèm ẩm thực châu Á?", ctaDesc: "Đặt hàng trực tuyến hoặc ghé thăm chúng tôi tại Ledergasse 44–46.", ctaBtn: "Đặt hàng ngay" },
    menu: { title: "Thực đơn", subtitle: "Chế biến tươi — mỗi ngày." },
    order: { title: "Đặt món", subtitle: "Chọn món và chúng tôi sẽ xác nhận qua điện thoại.", phoneDirect: "Gọi trực tiếp:", cartTitle: "Giỏ hàng", cartEmpty: "Giỏ hàng trống", cartEmptyHint: "Chọn món ăn để bắt đầu", total: "Tổng cộng", checkout: "Thanh toán", phoneAlt: "Muốn đặt qua điện thoại?", small: "Nhỏ", large: "Lớn", addToCart: "Thêm vào giỏ", sauceNote: "Gồm nước sốt: tương đậu nành, sốt chua ngọt hoặc cà ri Thái với nước cốt dừa" },
    about: { title: "Về chúng tôi", subtitle: "Ẩm thực châu Á chính thống giữa lòng Schwäbisch Gmünd.", storyTag: "Câu chuyện của chúng tôi", whoTag: "Chúng tôi là ai", whoTitle: "Nấu ăn bằng đam mê", whoDesc: "LYS Noodle Box đại diện cho ẩm thực châu Á chính thống từ trái tim. Bắt đầu như một bếp gia đình nhỏ, ngày nay đã trở thành một phần không thể thiếu của ẩm thực Gmünd.", drivesTag: "Động lực của chúng tôi", drivesTitle: "Điều thúc đẩy chúng tôi", valueHeart: "Bằng cả trái tim", valueHeartDesc: "Mỗi món ăn được chế biến với đam mê và tâm huyết thực sự — không phải đồ ăn nhanh, mà là bếp ăn thực sự.", valueFresh: "Nguyên liệu tươi", valueFreshDesc: "Chúng tôi dùng nguyên liệu tươi, chất lượng cao mỗi ngày — không thỏa hiệp.", valueFamily: "Gia đình", valueFamilyDesc: "Là doanh nghiệp gia đình, sự ấm áp và lòng hiếu khách luôn được đặt lên hàng đầu.", valueLocal: "Gắn bó địa phương", valueLocalDesc: "Ngay giữa Schwäbisch Gmünd — người hàng xóm ẩm thực châu Á của bạn nhiều năm qua.", hoursTag: "Luôn sẵn sàng phục vụ", hoursTitle: "Giờ mở cửa", addressTag: "Tìm chúng tôi", addressTitle: "Địa chỉ", mondayFriday: "Thứ Hai – Thứ Sáu", saturdayHours: "Thứ Bảy", sundayClosed: "Đóng cửa" },
    contact: { title: "Liên hệ", subtitle: "Nhắn tin cho chúng tôi", reachTitle: "Cách liên hệ với chúng tôi", phoneLabel: "Điện thoại", phoneHint: "Cách nhanh nhất để liên hệ là qua điện thoại", addressLabel: "Địa chỉ", hoursLabel: "Giờ mở cửa", hoursMoSa: "T2–T7: 11:00–20:30", hoursSun: "Chủ nhật đóng cửa", mapsBtn: "Mở trong Google Maps", msgTitle: "Gửi tin nhắn", thankYouTitle: "Cảm ơn tin nhắn của bạn!", thankYouDesc: "Chúng tôi sẽ liên hệ với bạn sớm nhất có thể.", nameLabel: "Họ tên", namePlaceholder: "Nguyễn Văn A", emailLabel: "Email", emailPlaceholder: "email@cua.ban", msgLabel: "Tin nhắn", msgPlaceholder: "Chúng tôi có thể giúp gì cho bạn?", sendBtn: "Gửi tin nhắn" },
    careers: { title: "Tuyển dụng", subtitle: "Gia nhập đội ngũ của chúng tôi" },
    checkout: { title: "Thanh toán", backToOrder: "Quay lại đặt hàng", yourDetails: "Thông tin của bạn", nameLabel: "Họ tên *", phoneLabelReq: "Số điện thoại *", emailLabel: "Email", notesLabel: "Ghi chú đơn hàng", notesPlaceholder: "VD: không cay, thêm sốt…", pickupOrDelivery: "Nhận tại cửa hàng hay giao hàng", pickup: "🏪 Nhận tại cửa hàng", delivery: "🛵 Giao hàng (+2,00 €)", streetPlaceholder: "Số nhà và tên đường", zipPlaceholder: "Mã bưu chính", cityPlaceholder: "Thành phố", payment: "Thanh toán", continueBtn: "Tiến hành thanh toán", editDetails: "Chỉnh sửa thông tin", securePayment: "Thanh toán an toàn", orderSummary: "Đơn hàng", subtotal: "Tạm tính", deliveryFee: "Phí giao hàng", total: "Tổng cộng", sslNote: "Thanh toán mã hóa SSL", thankYou: "Cảm ơn bạn!", thankYouMsg: "Đơn hàng của bạn đã được đặt thành công", thankYouPhone: "Chúng tôi sẽ gọi điện xác nhận.", backHome: "Về trang chủ", cartEmpty: "Giỏ hàng của bạn trống.", cartEmptyLink: "Quay lại đặt hàng", loading: "Đang tải…" },
    footer: { tagline: "Ẩm thực châu Á chính thống tại Schwäbisch Gmünd.", rights: "Bảo lưu mọi quyền." },
  },

  en: {
    langName: "English", flag: "🇬🇧", dir: "ltr",
    nav: { home: "Home", menu: "Menu", order: "Order", about: "About", contact: "Contact", careers: "Careers" },
    common: { orderNow: "Order now", viewMenu: "View menu", viewFullMenu: "Full menu", learnMore: "Learn more", phone: "Phone", address: "Address", openingHours: "Opening hours", closed: "Closed", monday: "Monday", saturday: "Saturday", sunday: "Sunday" },
    home: { heroDesc: "Authentic Asian cuisine — from crispy spring rolls and fried rice to aromatic Thai curries. Freshly prepared, served with love.", categoriesTitle: "What makes us special", noodleBox: "Noodle Box", noodleBoxDesc: "Fried noodles or rice, freshly prepared", curry: "Thai Curry", curryDesc: "Creamy coconut milk, fresh herbs", springRolls: "Spring Rolls", springRollsDesc: "Crispy fried, homemade sauce", freshTitle: "Fresh ingredients, prepared daily", freshDesc: "We use fresh vegetables, high-quality meat and selected spices every day — no compromise on quality.", testimonialsTitle: "What our guests say", testimonialQuote: "\"The best Asian restaurant in Schwäbisch Gmünd! The Noodle Box is simply unbeatable — fresh, spicy and always perfect.\"", testimonialAuthor: "— Maria S., loyal regular customer", ctaTitle: "Craving Asian food?", ctaDesc: "Order online now or visit us at Ledergasse 44–46.", ctaBtn: "Order online" },
    menu: { title: "Menu", subtitle: "Freshly prepared — every day." },
    order: { title: "Order", subtitle: "Select your dishes and we will call to confirm.", phoneDirect: "Call directly:", cartTitle: "Cart", cartEmpty: "Your cart is empty", cartEmptyHint: "Select dishes to start", total: "Total", checkout: "Checkout", phoneAlt: "Prefer to order by phone?", small: "Small", large: "Large", addToCart: "Add", sauceNote: "Incl. sauce: soy sauce, sweet and sour or Thai curry with coconut milk" },
    about: { title: "About us", subtitle: "Authentic Asian cuisine in the heart of Schwäbisch Gmünd.", storyTag: "Our story", whoTag: "Who we are", whoTitle: "Passionate about flavour", whoDesc: "LYS Noodle Box stands for authentic Asian cuisine with heart. What started as a small family kitchen is now an integral part of the Gmünd dining scene.", drivesTag: "What drives us", drivesTitle: "What drives us", valueHeart: "With heart", valueHeartDesc: "Every dish is prepared with genuine passion and care — not fast food, but real cooking.", valueFresh: "Fresh ingredients", valueFreshDesc: "We use fresh, high-quality ingredients every day — no compromises.", valueFamily: "Family-run", valueFamilyDesc: "As a family business, warmth and personal hospitality come first.", valueLocal: "Locally rooted", valueLocalDesc: "Right in the heart of Schwäbisch Gmünd — your neighbour for Asian specialities.", hoursTag: "Always here for you", hoursTitle: "Opening hours", addressTag: "Find us", addressTitle: "Address", mondayFriday: "Monday – Friday", saturdayHours: "Saturday", sundayClosed: "Closed" },
    contact: { title: "Contact", subtitle: "Send us a message", reachTitle: "How to reach us", phoneLabel: "Phone", phoneHint: "The fastest way to reach us is by phone", addressLabel: "Address", hoursLabel: "Opening hours", hoursMoSa: "Mon–Sat: 11:00–20:30", hoursSun: "Sunday closed", mapsBtn: "Open in Google Maps", msgTitle: "Send a message", thankYouTitle: "Thank you for your message!", thankYouDesc: "We will get back to you as soon as possible.", nameLabel: "Name", namePlaceholder: "John Smith", emailLabel: "Email", emailPlaceholder: "your@email.com", msgLabel: "Message", msgPlaceholder: "How can we help you?", sendBtn: "Send message" },
    careers: { title: "Careers", subtitle: "Join our team" },
    checkout: { title: "Checkout", backToOrder: "Back to order", yourDetails: "Your details", nameLabel: "Name *", phoneLabelReq: "Phone *", emailLabel: "Email", notesLabel: "Order notes", notesPlaceholder: "e.g. no spice, extra sauce…", pickupOrDelivery: "Pickup or delivery", pickup: "🏪 Pickup", delivery: "🛵 Delivery (+€2.00)", streetPlaceholder: "Street and number", zipPlaceholder: "ZIP code", cityPlaceholder: "City", payment: "Payment", continueBtn: "Continue to payment", editDetails: "Edit details", securePayment: "Secure payment", orderSummary: "Order", subtotal: "Subtotal", deliveryFee: "Delivery fee", total: "Total", sslNote: "SSL-encrypted payment", thankYou: "Thank you!", thankYouMsg: "Your order has been placed successfully", thankYouPhone: "We will call to confirm.", backHome: "Back to homepage", cartEmpty: "Your cart is empty.", cartEmptyLink: "Back to order", loading: "Loading…" },
    footer: { tagline: "Authentic Asian cuisine in Schwäbisch Gmünd.", rights: "All rights reserved." },
  },

  fr: {
    langName: "Français", flag: "🇫🇷", dir: "ltr",
    nav: { home: "Accueil", menu: "Menu", order: "Commander", about: "À propos", contact: "Contact", careers: "Emplois" },
    common: { orderNow: "Commander", viewMenu: "Voir le menu", viewFullMenu: "Menu complet", learnMore: "En savoir plus", phone: "Téléphone", address: "Adresse", openingHours: "Horaires", closed: "Fermé", monday: "Lundi", saturday: "Samedi", sunday: "Dimanche" },
    home: { heroDesc: "Cuisine asiatique authentique — des nems croustillants au riz sauté en passant par les curries thaïs parfumés. Préparé frais, servi avec amour.", categoriesTitle: "Ce qui nous rend spéciaux", noodleBox: "Noodle Box", noodleBoxDesc: "Nouilles ou riz sautés, préparés frais", curry: "Curry Thaï", curryDesc: "Lait de coco crémeux, herbes fraîches", springRolls: "Nems", springRollsDesc: "Frits croustillants, sauce maison", freshTitle: "Ingrédients frais, préparés chaque jour", freshDesc: "Nous utilisons des légumes frais, de la viande de qualité et des épices sélectionnées — sans compromis sur la qualité.", testimonialsTitle: "Ce que disent nos clients", testimonialQuote: "\"Le meilleur restaurant asiatique de Schwäbisch Gmünd ! La Noodle Box est tout simplement imbattable.\"", testimonialAuthor: "— Maria S., cliente fidèle", ctaTitle: "Envie d'Asie ?", ctaDesc: "Commandez en ligne ou venez nous voir au Ledergasse 44–46.", ctaBtn: "Commander en ligne" },
    menu: { title: "Menu", subtitle: "Préparé frais — chaque jour." },
    order: { title: "Commander", subtitle: "Choisissez vos plats et nous vous appelons pour confirmer.", phoneDirect: "Appeler directement :", cartTitle: "Panier", cartEmpty: "Votre panier est vide", cartEmptyHint: "Sélectionnez des plats", total: "Total", checkout: "Passer commande", phoneAlt: "Préférez commander par téléphone ?", small: "Petit", large: "Grand", addToCart: "Ajouter", sauceNote: "Incl. sauce : soja, aigre-douce ou curry thaï à la noix de coco" },
    about: { title: "À propos", subtitle: "Cuisine asiatique authentique au cœur de Schwäbisch Gmünd.", storyTag: "Notre histoire", whoTag: "Qui sommes-nous", whoTitle: "La passion du goût", whoDesc: "LYS Noodle Box représente la cuisine asiatique authentique avec du cœur. Commencé comme une petite cuisine familiale, c'est aujourd'hui une institution gastronomique de Gmünd.", drivesTag: "Ce qui nous motive", drivesTitle: "Ce qui nous motive", valueHeart: "Avec le cœur", valueHeartDesc: "Chaque plat est préparé avec une vraie passion — pas du fast food, mais une vraie cuisine.", valueFresh: "Ingrédients frais", valueFreshDesc: "Nous utilisons des ingrédients frais et de qualité chaque jour — sans compromis.", valueFamily: "Familial", valueFamilyDesc: "En tant qu'entreprise familiale, la chaleur et l'hospitalité passent en premier.", valueLocal: "Ancré localement", valueLocalDesc: "Au cœur de Schwäbisch Gmünd — votre voisin pour les spécialités asiatiques.", hoursTag: "Toujours là pour vous", hoursTitle: "Horaires d'ouverture", addressTag: "Nous trouver", addressTitle: "Adresse", mondayFriday: "Lundi – Vendredi", saturdayHours: "Samedi", sundayClosed: "Fermé" },
    contact: { title: "Contact", subtitle: "Écrivez-nous", reachTitle: "Comment nous contacter", phoneLabel: "Téléphone", phoneHint: "Le moyen le plus rapide est par téléphone", addressLabel: "Adresse", hoursLabel: "Horaires", hoursMoSa: "Lun–Sam : 11h00–20h30", hoursSun: "Dimanche fermé", mapsBtn: "Ouvrir dans Google Maps", msgTitle: "Envoyer un message", thankYouTitle: "Merci pour votre message !", thankYouDesc: "Nous vous répondrons dès que possible.", nameLabel: "Nom", namePlaceholder: "Jean Dupont", emailLabel: "E-mail", emailPlaceholder: "votre@email.fr", msgLabel: "Message", msgPlaceholder: "Comment pouvons-nous vous aider ?", sendBtn: "Envoyer" },
    careers: { title: "Emplois", subtitle: "Rejoignez notre équipe" },
    checkout: { title: "Paiement", backToOrder: "Retour à la commande", yourDetails: "Vos coordonnées", nameLabel: "Nom *", phoneLabelReq: "Téléphone *", emailLabel: "E-mail", notesLabel: "Notes de commande", notesPlaceholder: "ex. sans épices, sauce supplémentaire…", pickupOrDelivery: "Retrait ou livraison", pickup: "🏪 Retrait", delivery: "🛵 Livraison (+2,00 €)", streetPlaceholder: "Rue et numéro", zipPlaceholder: "Code postal", cityPlaceholder: "Ville", payment: "Paiement", continueBtn: "Continuer vers le paiement", editDetails: "Modifier les données", securePayment: "Paiement sécurisé", orderSummary: "Commande", subtotal: "Sous-total", deliveryFee: "Frais de livraison", total: "Total", sslNote: "Paiement crypté SSL", thankYou: "Merci !", thankYouMsg: "Votre commande a été passée avec succès", thankYouPhone: "Nous vous appellerons pour confirmer.", backHome: "Retour à l'accueil", cartEmpty: "Votre panier est vide.", cartEmptyLink: "Retour à la commande", loading: "Chargement…" },
    footer: { tagline: "Cuisine asiatique authentique à Schwäbisch Gmünd.", rights: "Tous droits réservés." },
  },

  es: {
    langName: "Español", flag: "🇪🇸", dir: "ltr",
    nav: { home: "Inicio", menu: "Menú", order: "Pedir", about: "Sobre nosotros", contact: "Contacto", careers: "Empleo" },
    common: { orderNow: "Pedir ahora", viewMenu: "Ver menú", viewFullMenu: "Menú completo", learnMore: "Más información", phone: "Teléfono", address: "Dirección", openingHours: "Horario", closed: "Cerrado", monday: "Lunes", saturday: "Sábado", sunday: "Domingo" },
    home: { heroDesc: "Cocina asiática auténtica — desde rollitos de primavera crujientes hasta curris tailandeses aromáticos. Preparado fresco, servido con amor.", categoriesTitle: "Lo que nos hace especiales", noodleBox: "Noodle Box", noodleBoxDesc: "Fideos o arroz fritos, preparados frescos", curry: "Curry Tailandés", curryDesc: "Leche de coco cremosa, hierbas frescas", springRolls: "Rollitos de Primavera", springRollsDesc: "Fritos crujientes, salsa casera", freshTitle: "Ingredientes frescos, preparados cada día", freshDesc: "Usamos verduras frescas, carne de calidad y especias seleccionadas — sin compromiso en la calidad.", testimonialsTitle: "Lo que dicen nuestros clientes", testimonialQuote: "\"¡El mejor restaurante asiático de Schwäbisch Gmünd! La Noodle Box es simplemente insuperable.\"", testimonialAuthor: "— Maria S., clienta fiel", ctaTitle: "¿Antojo de Asia?", ctaDesc: "Pide en línea o visítanos en Ledergasse 44–46.", ctaBtn: "Pedir en línea" },
    menu: { title: "Menú", subtitle: "Preparado fresco — cada día." },
    order: { title: "Pedir", subtitle: "Elige tus platos y te llamamos para confirmar.", phoneDirect: "Llamar directamente:", cartTitle: "Carrito", cartEmpty: "Tu carrito está vacío", cartEmptyHint: "Selecciona platos", total: "Total", checkout: "Finalizar pedido", phoneAlt: "¿Prefieres pedir por teléfono?", small: "Pequeño", large: "Grande", addToCart: "Añadir", sauceNote: "Incl. salsa: soja, agridulce o curry tailandés con leche de coco" },
    about: { title: "Sobre nosotros", subtitle: "Cocina asiática auténtica en el corazón de Schwäbisch Gmünd.", storyTag: "Nuestra historia", whoTag: "Quiénes somos", whoTitle: "Pasión por el sabor", whoDesc: "LYS Noodle Box representa la cocina asiática auténtica con corazón.", drivesTag: "Lo que nos motiva", drivesTitle: "Lo que nos motiva", valueHeart: "Con corazón", valueHeartDesc: "Cada plato se prepara con verdadera pasión — no comida rápida, sino cocina real.", valueFresh: "Ingredientes frescos", valueFreshDesc: "Usamos ingredientes frescos y de calidad cada día — sin compromisos.", valueFamily: "Familiar", valueFamilyDesc: "Como empresa familiar, la calidez y la hospitalidad son lo primero.", valueLocal: "Arraigados localmente", valueLocalDesc: "En el corazón de Schwäbisch Gmünd — tu vecino de especialidades asiáticas.", hoursTag: "Siempre aquí para ti", hoursTitle: "Horario de apertura", addressTag: "Encuéntranos", addressTitle: "Dirección", mondayFriday: "Lunes – Viernes", saturdayHours: "Sábado", sundayClosed: "Cerrado" },
    contact: { title: "Contacto", subtitle: "Escríbenos", reachTitle: "Cómo contactarnos", phoneLabel: "Teléfono", phoneHint: "La forma más rápida es por teléfono", addressLabel: "Dirección", hoursLabel: "Horario", hoursMoSa: "Lun–Sáb: 11:00–20:30", hoursSun: "Domingo cerrado", mapsBtn: "Abrir en Google Maps", msgTitle: "Enviar mensaje", thankYouTitle: "¡Gracias por tu mensaje!", thankYouDesc: "Te responderemos lo antes posible.", nameLabel: "Nombre", namePlaceholder: "Juan García", emailLabel: "Correo electrónico", emailPlaceholder: "tu@email.es", msgLabel: "Mensaje", msgPlaceholder: "¿Cómo podemos ayudarte?", sendBtn: "Enviar mensaje" },
    careers: { title: "Empleo", subtitle: "Únete a nuestro equipo" },
    checkout: { title: "Caja", backToOrder: "Volver al pedido", yourDetails: "Tus datos", nameLabel: "Nombre *", phoneLabelReq: "Teléfono *", emailLabel: "Correo electrónico", notesLabel: "Notas del pedido", notesPlaceholder: "ej. sin picante, salsa extra…", pickupOrDelivery: "Recogida o entrega", pickup: "🏪 Recogida", delivery: "🛵 Entrega (+2,00 €)", streetPlaceholder: "Calle y número", zipPlaceholder: "Código postal", cityPlaceholder: "Ciudad", payment: "Pago", continueBtn: "Continuar al pago", editDetails: "Editar datos", securePayment: "Pago seguro", orderSummary: "Pedido", subtotal: "Subtotal", deliveryFee: "Gastos de envío", total: "Total", sslNote: "Pago cifrado SSL", thankYou: "¡Muchas gracias!", thankYouMsg: "Tu pedido ha sido realizado con éxito", thankYouPhone: "Te llamaremos para confirmar.", backHome: "Volver al inicio", cartEmpty: "Tu carrito está vacío.", cartEmptyLink: "Volver al pedido", loading: "Cargando…" },
    footer: { tagline: "Cocina asiática auténtica en Schwäbisch Gmünd.", rights: "Todos los derechos reservados." },
  },

  it: {
    langName: "Italiano", flag: "🇮🇹", dir: "ltr",
    nav: { home: "Home", menu: "Menu", order: "Ordina", about: "Chi siamo", contact: "Contatti", careers: "Lavora con noi" },
    common: { orderNow: "Ordina ora", viewMenu: "Vedi menu", viewFullMenu: "Menu completo", learnMore: "Scopri di più", phone: "Telefono", address: "Indirizzo", openingHours: "Orari", closed: "Chiuso", monday: "Lunedì", saturday: "Sabato", sunday: "Domenica" },
    home: { heroDesc: "Cucina asiatica autentica — dai croccanti involtini primavera al riso fritto fino ai curry tailandesi aromatici. Fresco ogni giorno, servito con amore.", categoriesTitle: "Cosa ci rende speciali", noodleBox: "Noodle Box", noodleBoxDesc: "Noodle o riso fritto, preparato fresco", curry: "Curry Tailandese", curryDesc: "Latte di cocco cremoso, erbe fresche", springRolls: "Involtini Primavera", springRollsDesc: "Fritti croccanti, salsa fatta in casa", freshTitle: "Ingredienti freschi, preparati ogni giorno", freshDesc: "Usiamo verdure fresche, carne di qualità e spezie selezionate ogni giorno — senza compromessi.", testimonialsTitle: "Cosa dicono i nostri clienti", testimonialQuote: "\"Il miglior ristorante asiatico di Schwäbisch Gmünd! La Noodle Box è semplicemente imbattibile.\"", testimonialAuthor: "— Maria S., cliente fedele", ctaTitle: "Voglia di Asia?", ctaDesc: "Ordina online o vienici a trovare in Ledergasse 44–46.", ctaBtn: "Ordina online" },
    menu: { title: "Menu", subtitle: "Preparato fresco — ogni giorno." },
    order: { title: "Ordina", subtitle: "Scegli i tuoi piatti e ti chiamiamo per confermare.", phoneDirect: "Chiama direttamente:", cartTitle: "Carrello", cartEmpty: "Il carrello è vuoto", cartEmptyHint: "Seleziona i piatti", total: "Totale", checkout: "Vai alla cassa", phoneAlt: "Preferisci ordinare per telefono?", small: "Piccolo", large: "Grande", addToCart: "Aggiungi", sauceNote: "Incl. salsa: soia, agrodolce o curry tailandese al cocco" },
    about: { title: "Chi siamo", subtitle: "Cucina asiatica autentica nel cuore di Schwäbisch Gmünd.", storyTag: "La nostra storia", whoTag: "Chi siamo", whoTitle: "Passione per il sapore", whoDesc: "LYS Noodle Box rappresenta la cucina asiatica autentica con il cuore.", drivesTag: "Cosa ci motiva", drivesTitle: "Cosa ci motiva", valueHeart: "Con il cuore", valueHeartDesc: "Ogni piatto è preparato con vera passione — non fast food, ma cucina vera.", valueFresh: "Ingredienti freschi", valueFreshDesc: "Usiamo ingredienti freschi e di qualità ogni giorno — senza compromessi.", valueFamily: "Familiare", valueFamilyDesc: "Come azienda familiare, il calore e l'ospitalità vengono prima di tutto.", valueLocal: "Radicati nel territorio", valueLocalDesc: "Nel cuore di Schwäbisch Gmünd — il tuo vicino di specialità asiatiche.", hoursTag: "Sempre qui per te", hoursTitle: "Orari di apertura", addressTag: "Trovaci", addressTitle: "Indirizzo", mondayFriday: "Lunedì – Venerdì", saturdayHours: "Sabato", sundayClosed: "Chiuso" },
    contact: { title: "Contatti", subtitle: "Scrivici", reachTitle: "Come contattarci", phoneLabel: "Telefono", phoneHint: "Il modo più veloce è per telefono", addressLabel: "Indirizzo", hoursLabel: "Orari", hoursMoSa: "Lun–Sab: 11:00–20:30", hoursSun: "Domenica chiuso", mapsBtn: "Apri in Google Maps", msgTitle: "Invia un messaggio", thankYouTitle: "Grazie per il tuo messaggio!", thankYouDesc: "Ti risponderemo il prima possibile.", nameLabel: "Nome", namePlaceholder: "Mario Rossi", emailLabel: "Email", emailPlaceholder: "tua@email.it", msgLabel: "Messaggio", msgPlaceholder: "Come possiamo aiutarti?", sendBtn: "Invia messaggio" },
    careers: { title: "Lavora con noi", subtitle: "Unisciti al nostro team" },
    checkout: { title: "Cassa", backToOrder: "Torna all'ordine", yourDetails: "I tuoi dati", nameLabel: "Nome *", phoneLabelReq: "Telefono *", emailLabel: "Email", notesLabel: "Note sull'ordine", notesPlaceholder: "es. senza piccante, salsa extra…", pickupOrDelivery: "Ritiro o consegna", pickup: "🏪 Ritiro", delivery: "🛵 Consegna (+2,00 €)", streetPlaceholder: "Via e numero", zipPlaceholder: "CAP", cityPlaceholder: "Città", payment: "Pagamento", continueBtn: "Continua al pagamento", editDetails: "Modifica dati", securePayment: "Pagamento sicuro", orderSummary: "Ordine", subtotal: "Subtotale", deliveryFee: "Spese di consegna", total: "Totale", sslNote: "Pagamento criptato SSL", thankYou: "Grazie mille!", thankYouMsg: "Il tuo ordine è stato effettuato con successo", thankYouPhone: "Ti chiameremo per confermare.", backHome: "Torna alla homepage", cartEmpty: "Il tuo carrello è vuoto.", cartEmptyLink: "Torna all'ordine", loading: "Caricamento…" },
    footer: { tagline: "Cucina asiatica autentica a Schwäbisch Gmünd.", rights: "Tutti i diritti riservati." },
  },

  pt: {
    langName: "Português", flag: "🇵🇹", dir: "ltr",
    nav: { home: "Início", menu: "Menu", order: "Encomendar", about: "Sobre nós", contact: "Contacto", careers: "Carreiras" },
    common: { orderNow: "Encomendar agora", viewMenu: "Ver menu", viewFullMenu: "Menu completo", learnMore: "Saber mais", phone: "Telefone", address: "Endereço", openingHours: "Horário", closed: "Fechado", monday: "Segunda-feira", saturday: "Sábado", sunday: "Domingo" },
    home: { heroDesc: "Cozinha asiática autêntica — desde rolinhos de primavera crocantes ao arroz frito até caril tailandeses aromáticos. Preparado fresco, servido com amor.", categoriesTitle: "O que nos torna especiais", noodleBox: "Noodle Box", noodleBoxDesc: "Noodles ou arroz fritos, preparados frescos", curry: "Caril Tailandês", curryDesc: "Leite de coco cremoso, ervas frescas", springRolls: "Rolinhos de Primavera", springRollsDesc: "Fritos crocantes, molho caseiro", freshTitle: "Ingredientes frescos, preparados diariamente", freshDesc: "Usamos legumes frescos, carne de qualidade e especiarias selecionadas — sem compromissos.", testimonialsTitle: "O que dizem os nossos clientes", testimonialQuote: "\"O melhor restaurante asiático de Schwäbisch Gmünd! A Noodle Box é simplesmente imbatível.\"", testimonialAuthor: "— Maria S., cliente fiel", ctaTitle: "Com vontade de Ásia?", ctaDesc: "Encomende online ou visite-nos na Ledergasse 44–46.", ctaBtn: "Encomendar online" },
    menu: { title: "Menu", subtitle: "Preparado fresco — todos os dias." },
    order: { title: "Encomendar", subtitle: "Escolha os seus pratos e ligamos para confirmar.", phoneDirect: "Ligar diretamente:", cartTitle: "Carrinho", cartEmpty: "O carrinho está vazio", cartEmptyHint: "Selecione pratos", total: "Total", checkout: "Finalizar", phoneAlt: "Prefere encomendar por telefone?", small: "Pequeno", large: "Grande", addToCart: "Adicionar", sauceNote: "Incl. molho: soja, agridoce ou caril tailandês com leite de coco" },
    about: { title: "Sobre nós", subtitle: "Cozinha asiática autêntica no coração de Schwäbisch Gmünd.", storyTag: "A nossa história", whoTag: "Quem somos", whoTitle: "Paixão pelo sabor", whoDesc: "LYS Noodle Box representa a cozinha asiática autêntica com coração.", drivesTag: "O que nos motiva", drivesTitle: "O que nos motiva", valueHeart: "Com coração", valueHeartDesc: "Cada prato é preparado com verdadeira paixão — não fast food, mas cozinha real.", valueFresh: "Ingredientes frescos", valueFreshDesc: "Usamos ingredientes frescos e de qualidade todos os dias — sem compromissos.", valueFamily: "Familiar", valueFamilyDesc: "Como empresa familiar, o calor e a hospitalidade vêm primeiro.", valueLocal: "Enraizados localmente", valueLocalDesc: "No coração de Schwäbisch Gmünd — o seu vizinho de especialidades asiáticas.", hoursTag: "Sempre aqui para si", hoursTitle: "Horário de funcionamento", addressTag: "Encontre-nos", addressTitle: "Endereço", mondayFriday: "Segunda – Sexta", saturdayHours: "Sábado", sundayClosed: "Fechado" },
    contact: { title: "Contacto", subtitle: "Escreva-nos", reachTitle: "Como nos contactar", phoneLabel: "Telefone", phoneHint: "A forma mais rápida é por telefone", addressLabel: "Endereço", hoursLabel: "Horário", hoursMoSa: "Seg–Sáb: 11:00–20:30", hoursSun: "Domingo fechado", mapsBtn: "Abrir no Google Maps", msgTitle: "Enviar mensagem", thankYouTitle: "Obrigado pela sua mensagem!", thankYouDesc: "Responderemos o mais rapidamente possível.", nameLabel: "Nome", namePlaceholder: "João Silva", emailLabel: "Email", emailPlaceholder: "seu@email.pt", msgLabel: "Mensagem", msgPlaceholder: "Como podemos ajudar?", sendBtn: "Enviar mensagem" },
    careers: { title: "Carreiras", subtitle: "Junte-se à nossa equipa" },
    checkout: { title: "Caixa", backToOrder: "Voltar à encomenda", yourDetails: "Os seus dados", nameLabel: "Nome *", phoneLabelReq: "Telefone *", emailLabel: "Email", notesLabel: "Notas da encomenda", notesPlaceholder: "ex. sem picante, molho extra…", pickupOrDelivery: "Recolha ou entrega", pickup: "🏪 Recolha", delivery: "🛵 Entrega (+2,00 €)", streetPlaceholder: "Rua e número", zipPlaceholder: "Código postal", cityPlaceholder: "Cidade", payment: "Pagamento", continueBtn: "Continuar para pagamento", editDetails: "Editar dados", securePayment: "Pagamento seguro", orderSummary: "Encomenda", subtotal: "Subtotal", deliveryFee: "Taxa de entrega", total: "Total", sslNote: "Pagamento encriptado SSL", thankYou: "Muito obrigado!", thankYouMsg: "A sua encomenda foi efetuada com sucesso", thankYouPhone: "Ligaremos para confirmar.", backHome: "Voltar ao início", cartEmpty: "O seu carrinho está vazio.", cartEmptyLink: "Voltar à encomenda", loading: "A carregar…" },
    footer: { tagline: "Cozinha asiática autêntica em Schwäbisch Gmünd.", rights: "Todos os direitos reservados." },
  },

  pl: {
    langName: "Polski", flag: "🇵🇱", dir: "ltr",
    nav: { home: "Strona główna", menu: "Menu", order: "Zamów", about: "O nas", contact: "Kontakt", careers: "Kariera" },
    common: { orderNow: "Zamów teraz", viewMenu: "Zobacz menu", viewFullMenu: "Pełne menu", learnMore: "Dowiedz się więcej", phone: "Telefon", address: "Adres", openingHours: "Godziny otwarcia", closed: "Zamknięte", monday: "Poniedziałek", saturday: "Sobota", sunday: "Niedziela" },
    home: { heroDesc: "Autentyczna kuchnia azjatycka — od chrupiących sajgonek po smażony ryż i aromatyczne curry tajskie. Świeżo przygotowane, podawane z miłością.", categoriesTitle: "Co nas wyróżnia", noodleBox: "Noodle Box", noodleBoxDesc: "Smażony makaron lub ryż, świeżo przygotowany", curry: "Curry Tajskie", curryDesc: "Kremowe mleko kokosowe, świeże zioła", springRolls: "Sajgonki", springRollsDesc: "Chrupiące, domowy sos", freshTitle: "Świeże składniki, przygotowywane codziennie", freshDesc: "Używamy świeżych warzyw, wysokiej jakości mięsa i wybranych przypraw — bez kompromisów.", testimonialsTitle: "Co mówią nasi goście", testimonialQuote: "\"Najlepsza azjatycka restauracja w Schwäbisch Gmünd! Noodle Box jest po prostu niepokonana.\"", testimonialAuthor: "— Maria S., wierna klientka", ctaTitle: "Masz ochotę na Azję?", ctaDesc: "Zamów online lub odwiedź nas przy Ledergasse 44–46.", ctaBtn: "Zamów online" },
    menu: { title: "Menu", subtitle: "Świeżo przygotowywane — każdego dnia." },
    order: { title: "Zamów", subtitle: "Wybierz dania, a my zadzwonimy, aby potwierdzić.", phoneDirect: "Zadzwoń bezpośrednio:", cartTitle: "Koszyk", cartEmpty: "Koszyk jest pusty", cartEmptyHint: "Wybierz dania", total: "Łącznie", checkout: "Do kasy", phoneAlt: "Wolisz zamówić telefonicznie?", small: "Mały", large: "Duży", addToCart: "Dodaj", sauceNote: "W zestawie sos: sojowy, słodko-kwaśny lub tajskie curry z mlekiem kokosowym" },
    about: { title: "O nas", subtitle: "Autentyczna kuchnia azjatycka w sercu Schwäbisch Gmünd.", storyTag: "Nasza historia", whoTag: "Kim jesteśmy", whoTitle: "Pasja do smaku", whoDesc: "LYS Noodle Box to autentyczna kuchnia azjatycka z sercem.", drivesTag: "Co nas napędza", drivesTitle: "Co nas napędza", valueHeart: "Z sercem", valueHeartDesc: "Każde danie jest przygotowywane z prawdziwą pasją — nie fast food, ale prawdziwa kuchnia.", valueFresh: "Świeże składniki", valueFreshDesc: "Używamy świeżych, wysokiej jakości składników każdego dnia — bez kompromisów.", valueFamily: "Rodzinnie", valueFamilyDesc: "Jako firma rodzinna, ciepło i gościnność są na pierwszym miejscu.", valueLocal: "Zakorzenieni lokalnie", valueLocalDesc: "W samym sercu Schwäbisch Gmünd — Twój sąsiad w azjatyckich specjałach.", hoursTag: "Zawsze do Twojej dyspozycji", hoursTitle: "Godziny otwarcia", addressTag: "Znajdź nas", addressTitle: "Adres", mondayFriday: "Poniedziałek – Piątek", saturdayHours: "Sobota", sundayClosed: "Zamknięte" },
    contact: { title: "Kontakt", subtitle: "Napisz do nas", reachTitle: "Jak nas znaleźć", phoneLabel: "Telefon", phoneHint: "Najszybszy kontakt przez telefon", addressLabel: "Adres", hoursLabel: "Godziny otwarcia", hoursMoSa: "Pon–Sob: 11:00–20:30", hoursSun: "Niedziela zamknięte", mapsBtn: "Otwórz w Google Maps", msgTitle: "Wyślij wiadomość", thankYouTitle: "Dziękujemy za wiadomość!", thankYouDesc: "Odpowiemy jak najszybciej.", nameLabel: "Imię i nazwisko", namePlaceholder: "Jan Kowalski", emailLabel: "E-mail", emailPlaceholder: "twoj@email.pl", msgLabel: "Wiadomość", msgPlaceholder: "Jak możemy Ci pomóc?", sendBtn: "Wyślij wiadomość" },
    careers: { title: "Kariera", subtitle: "Dołącz do naszego zespołu" },
    checkout: { title: "Kasa", backToOrder: "Powrót do zamówienia", yourDetails: "Twoje dane", nameLabel: "Imię i nazwisko *", phoneLabelReq: "Telefon *", emailLabel: "E-mail", notesLabel: "Uwagi do zamówienia", notesPlaceholder: "np. bez ostrości, dodatkowy sos…", pickupOrDelivery: "Odbiór lub dostawa", pickup: "🏪 Odbiór", delivery: "🛵 Dostawa (+2,00 €)", streetPlaceholder: "Ulica i numer", zipPlaceholder: "Kod pocztowy", cityPlaceholder: "Miasto", payment: "Płatność", continueBtn: "Przejdź do płatności", editDetails: "Edytuj dane", securePayment: "Bezpieczna płatność", orderSummary: "Zamówienie", subtotal: "Suma częściowa", deliveryFee: "Opłata za dostawę", total: "Łącznie", sslNote: "Płatność szyfrowana SSL", thankYou: "Dziękujemy!", thankYouMsg: "Twoje zamówienie zostało złożone pomyślnie", thankYouPhone: "Zadzwonimy, aby potwierdzić.", backHome: "Powrót na stronę główną", cartEmpty: "Twój koszyk jest pusty.", cartEmptyLink: "Powrót do zamówienia", loading: "Ładowanie…" },
    footer: { tagline: "Autentyczna kuchnia azjatycka w Schwäbisch Gmünd.", rights: "Wszelkie prawa zastrzeżone." },
  },

  ru: {
    langName: "Русский", flag: "🇷🇺", dir: "ltr",
    nav: { home: "Главная", menu: "Меню", order: "Заказать", about: "О нас", contact: "Контакты", careers: "Вакансии" },
    common: { orderNow: "Заказать сейчас", viewMenu: "Смотреть меню", viewFullMenu: "Полное меню", learnMore: "Узнать больше", phone: "Телефон", address: "Адрес", openingHours: "Часы работы", closed: "Закрыто", monday: "Понедельник", saturday: "Суббота", sunday: "Воскресенье" },
    home: { heroDesc: "Аутентичная азиатская кухня — от хрустящих спринг-роллов до жареного риса и ароматных тайских карри. Готовим свежее каждый день с любовью.", categoriesTitle: "Что нас делает особенными", noodleBox: "Noodle Box", noodleBoxDesc: "Жареная лапша или рис, свежеприготовленные", curry: "Тайское карри", curryDesc: "Сливочное кокосовое молоко, свежие травы", springRolls: "Спринг-роллы", springRollsDesc: "Хрустящие во фритюре, домашний соус", freshTitle: "Свежие ингредиенты, готовятся каждый день", freshDesc: "Мы используем свежие овощи, мясо высокого качества и отборные специи — без компромиссов.", testimonialsTitle: "Отзывы наших гостей", testimonialQuote: "\"Лучший азиатский ресторан в Швебиш-Гмюнде! Noodle Box просто непревзойдённа.\"", testimonialAuthor: "— Мария С., постоянный клиент", ctaTitle: "Хочется азиатской еды?", ctaDesc: "Заказывайте онлайн или приходите к нам по адресу Ledergasse 44–46.", ctaBtn: "Заказать онлайн" },
    menu: { title: "Меню", subtitle: "Готовится свежим — каждый день." },
    order: { title: "Заказать", subtitle: "Выберите блюда, и мы перезвоним для подтверждения.", phoneDirect: "Позвонить напрямую:", cartTitle: "Корзина", cartEmpty: "Корзина пуста", cartEmptyHint: "Выберите блюда", total: "Итого", checkout: "Оформить заказ", phoneAlt: "Предпочитаете заказ по телефону?", small: "Маленький", large: "Большой", addToCart: "Добавить", sauceNote: "Вкл. соус: соевый, кисло-сладкий или тайское карри с кокосовым молоком" },
    about: { title: "О нас", subtitle: "Аутентичная азиатская кухня в сердце Швебиш-Гмюнда.", storyTag: "Наша история", whoTag: "Кто мы", whoTitle: "Страсть ко вкусу", whoDesc: "LYS Noodle Box — это аутентичная азиатская кухня с душой.", drivesTag: "Что нас движет", drivesTitle: "Что нас движет", valueHeart: "С душой", valueHeartDesc: "Каждое блюдо готовится с настоящей страстью — не фастфуд, а настоящая кухня.", valueFresh: "Свежие ингредиенты", valueFreshDesc: "Мы используем свежие, качественные ингредиенты каждый день — без компромиссов.", valueFamily: "Семейное дело", valueFamilyDesc: "Как семейный бизнес, теплота и гостеприимство на первом месте.", valueLocal: "Укоренившиеся местно", valueLocalDesc: "В самом сердце Швебиш-Гмюнда — ваш сосед по азиатским специалитетам.", hoursTag: "Всегда для вас", hoursTitle: "Часы работы", addressTag: "Найдите нас", addressTitle: "Адрес", mondayFriday: "Понедельник – Пятница", saturdayHours: "Суббота", sundayClosed: "Закрыто" },
    contact: { title: "Контакты", subtitle: "Напишите нам", reachTitle: "Как с нами связаться", phoneLabel: "Телефон", phoneHint: "Самый быстрый способ — позвонить", addressLabel: "Адрес", hoursLabel: "Часы работы", hoursMoSa: "Пн–Сб: 11:00–20:30", hoursSun: "Воскресенье закрыто", mapsBtn: "Открыть в Google Maps", msgTitle: "Отправить сообщение", thankYouTitle: "Спасибо за ваше сообщение!", thankYouDesc: "Мы ответим как можно скорее.", nameLabel: "Имя", namePlaceholder: "Иван Иванов", emailLabel: "Эл. почта", emailPlaceholder: "ваш@email.ru", msgLabel: "Сообщение", msgPlaceholder: "Чем мы можем помочь?", sendBtn: "Отправить" },
    careers: { title: "Вакансии", subtitle: "Присоединяйтесь к нашей команде" },
    checkout: { title: "Оформление", backToOrder: "Назад к заказу", yourDetails: "Ваши данные", nameLabel: "Имя *", phoneLabelReq: "Телефон *", emailLabel: "Эл. почта", notesLabel: "Примечания к заказу", notesPlaceholder: "напр. без острого, дополнительный соус…", pickupOrDelivery: "Самовывоз или доставка", pickup: "🏪 Самовывоз", delivery: "🛵 Доставка (+2,00 €)", streetPlaceholder: "Улица и номер дома", zipPlaceholder: "Почтовый индекс", cityPlaceholder: "Город", payment: "Оплата", continueBtn: "Перейти к оплате", editDetails: "Изменить данные", securePayment: "Безопасная оплата", orderSummary: "Заказ", subtotal: "Подытог", deliveryFee: "Стоимость доставки", total: "Итого", sslNote: "SSL-шифрование", thankYou: "Большое спасибо!", thankYouMsg: "Ваш заказ успешно оформлен", thankYouPhone: "Мы позвоним для подтверждения.", backHome: "На главную", cartEmpty: "Ваша корзина пуста.", cartEmptyLink: "Назад к заказу", loading: "Загрузка…" },
    footer: { tagline: "Аутентичная азиатская кухня в Швебиш-Гмюнде.", rights: "Все права защищены." },
  },

  tr: {
    langName: "Türkçe", flag: "🇹🇷", dir: "ltr",
    nav: { home: "Ana Sayfa", menu: "Menü", order: "Sipariş Ver", about: "Hakkımızda", contact: "İletişim", careers: "Kariyer" },
    common: { orderNow: "Şimdi sipariş ver", viewMenu: "Menüyü gör", viewFullMenu: "Tam menü", learnMore: "Daha fazla", phone: "Telefon", address: "Adres", openingHours: "Çalışma saatleri", closed: "Kapalı", monday: "Pazartesi", saturday: "Cumartesi", sunday: "Pazar" },
    home: { heroDesc: "Otantik Asya mutfağı — çıtır bahar rulolarından kızarmış pirince ve aromatik Tayland körilerine kadar. Her gün taze hazırlanmış, sevgiyle servis edilir.", categoriesTitle: "Bizi özel yapan", noodleBox: "Noodle Box", noodleBoxDesc: "Kızarmış noodle veya pilav, taze hazırlanmış", curry: "Tayland Körisi", curryDesc: "Kremsi hindistancevizi sütü, taze otlar", springRolls: "Bahar Rulolar", springRollsDesc: "Çıtır kızarmış, ev yapımı sos", freshTitle: "Her gün taze malzeme, taze hazırlanmış", freshDesc: "Her gün taze sebze, kaliteli et ve özenle seçilmiş baharatlar kullanıyoruz — kalitede taviz yok.", testimonialsTitle: "Misafirlerimiz ne diyor", testimonialQuote: "\"Schwäbisch Gmünd'daki en iyi Asya restoranı! Noodle Box gerçekten eşsiz.\"", testimonialAuthor: "— Maria S., sadık müşteri", ctaTitle: "Asya yemeği canınız mı çekiyor?", ctaDesc: "Hemen online sipariş verin veya Ledergasse 44–46'da bizi ziyaret edin.", ctaBtn: "Online sipariş ver" },
    menu: { title: "Menü", subtitle: "Her gün taze hazırlanmış." },
    order: { title: "Sipariş Ver", subtitle: "Yemeklerinizi seçin, onay için sizi arayacağız.", phoneDirect: "Doğrudan arayın:", cartTitle: "Sepet", cartEmpty: "Sepetiniz boş", cartEmptyHint: "Yemek seçin", total: "Toplam", checkout: "Ödemeye git", phoneAlt: "Telefonla sipariş vermeyi tercih eder misiniz?", small: "Küçük", large: "Büyük", addToCart: "Ekle", sauceNote: "Dahil sos: soya, tatlı-ekşi veya hindistancevizi sütlü Tayland körisi" },
    about: { title: "Hakkımızda", subtitle: "Schwäbisch Gmünd'ün kalbinde otantik Asya mutfağı.", storyTag: "Hikayemiz", whoTag: "Biz kimiz", whoTitle: "Lezzete olan tutku", whoDesc: "LYS Noodle Box, kalpten gelen otantik Asya mutfağını temsil eder.", drivesTag: "Bizi motive eden", drivesTitle: "Bizi motive eden", valueHeart: "Kalpten", valueHeartDesc: "Her yemek gerçek tutku ve özenle hazırlanır — fast food değil, gerçek mutfak.", valueFresh: "Taze malzemeler", valueFreshDesc: "Her gün taze, kaliteli malzeme kullanıyoruz — taviz yok.", valueFamily: "Aile işi", valueFamilyDesc: "Aile şirketi olarak sıcaklık ve misafirperverlik önce gelir.", valueLocal: "Yerel köklü", valueLocalDesc: "Schwäbisch Gmünd'ün kalbinde — Asya lezzetlerinde komşunuz.", hoursTag: "Her zaman sizin için", hoursTitle: "Çalışma saatleri", addressTag: "Bizi bulun", addressTitle: "Adres", mondayFriday: "Pazartesi – Cuma", saturdayHours: "Cumartesi", sundayClosed: "Kapalı" },
    contact: { title: "İletişim", subtitle: "Bize yazın", reachTitle: "Bize nasıl ulaşılır", phoneLabel: "Telefon", phoneHint: "En hızlı yol telefonla", addressLabel: "Adres", hoursLabel: "Çalışma saatleri", hoursMoSa: "Pzt–Cmt: 11:00–20:30", hoursSun: "Pazar kapalı", mapsBtn: "Google Maps'te aç", msgTitle: "Mesaj gönder", thankYouTitle: "Mesajınız için teşekkürler!", thankYouDesc: "En kısa sürede size geri döneceğiz.", nameLabel: "Ad Soyad", namePlaceholder: "Ahmet Yılmaz", emailLabel: "E-posta", emailPlaceholder: "sizin@email.tr", msgLabel: "Mesaj", msgPlaceholder: "Size nasıl yardımcı olabiliriz?", sendBtn: "Mesaj gönder" },
    careers: { title: "Kariyer", subtitle: "Ekibimize katılın" },
    checkout: { title: "Ödeme", backToOrder: "Siparişe dön", yourDetails: "Bilgileriniz", nameLabel: "Ad Soyad *", phoneLabelReq: "Telefon *", emailLabel: "E-posta", notesLabel: "Sipariş notları", notesPlaceholder: "örn. acısız, ekstra sos…", pickupOrDelivery: "Teslim alma veya teslimat", pickup: "🏪 Teslim alma", delivery: "🛵 Teslimat (+2,00 €)", streetPlaceholder: "Sokak ve numara", zipPlaceholder: "Posta kodu", cityPlaceholder: "Şehir", payment: "Ödeme", continueBtn: "Ödemeye devam et", editDetails: "Bilgileri düzenle", securePayment: "Güvenli ödeme", orderSummary: "Sipariş", subtotal: "Ara toplam", deliveryFee: "Teslimat ücreti", total: "Toplam", sslNote: "SSL şifreli ödeme", thankYou: "Çok teşekkürler!", thankYouMsg: "Siparişiniz başarıyla verildi", thankYouPhone: "Onay için sizi arayacağız.", backHome: "Ana sayfaya dön", cartEmpty: "Sepetiniz boş.", cartEmptyLink: "Siparişe dön", loading: "Yükleniyor…" },
    footer: { tagline: "Schwäbisch Gmünd'de otantik Asya mutfağı.", rights: "Tüm hakları saklıdır." },
  },

  ar: {
    langName: "العربية", flag: "🇸🇦", dir: "rtl",
    nav: { home: "الرئيسية", menu: "القائمة", order: "اطلب الآن", about: "من نحن", contact: "اتصل بنا", careers: "وظائف" },
    common: { orderNow: "اطلب الآن", viewMenu: "عرض القائمة", viewFullMenu: "القائمة الكاملة", learnMore: "اعرف المزيد", phone: "هاتف", address: "العنوان", openingHours: "ساعات العمل", closed: "مغلق", monday: "الاثنين", saturday: "السبت", sunday: "الأحد" },
    home: { heroDesc: "مطبخ آسيوي أصيل — من الربيع رول المقرمش إلى الأرز المقلي والكاري التايلاندي العطر. طازج يومياً، يُقدَّم بكل محبة.", categoriesTitle: "ما يميزنا", noodleBox: "نودل بوكس", noodleBoxDesc: "نودلز أو أرز مقلي، محضر طازج", curry: "كاري تايلاندي", curryDesc: "حليب جوز الهند الكريمي، أعشاب طازجة", springRolls: "ربيع رول", springRollsDesc: "مقرمش، صلصة منزلية", freshTitle: "مكونات طازجة، محضرة يومياً", freshDesc: "نستخدم خضاراً طازجاً ولحوماً عالية الجودة وتوابل مختارة كل يوم — لا تنازل عن الجودة.", testimonialsTitle: "ماذا يقول ضيوفنا", testimonialQuote: "\"أفضل مطعم آسيوي في شفيبيش غموند! نودل بوكس لا تُضاهى — طازجة ولذيذة دائماً.\"", testimonialAuthor: "— ماريا س.، عميلة وفية", ctaTitle: "شهيتك للمطبخ الآسيوي؟", ctaDesc: "اطلب عبر الإنترنت أو زرنا في Ledergasse 44–46.", ctaBtn: "اطلب عبر الإنترنت" },
    menu: { title: "القائمة", subtitle: "محضر طازج — كل يوم." },
    order: { title: "اطلب الآن", subtitle: "اختر أطباقك وسنتصل بك للتأكيد.", phoneDirect: "اتصل مباشرة:", cartTitle: "السلة", cartEmpty: "سلتك فارغة", cartEmptyHint: "اختر الأطباق", total: "المجموع", checkout: "إتمام الطلب", phoneAlt: "تفضل الطلب عبر الهاتف؟", small: "صغير", large: "كبير", addToCart: "أضف", sauceNote: "يشمل الصلصة: صويا، حلو ومالح، أو كاري تايلاندي بحليب جوز الهند" },
    about: { title: "من نحن", subtitle: "مطبخ آسيوي أصيل في قلب شفيبيش غموند.", storyTag: "قصتنا", whoTag: "من نحن", whoTitle: "شغف بالنكهة", whoDesc: "LYS Noodle Box يمثل المطبخ الآسيوي الأصيل من القلب.", drivesTag: "ما يحفزنا", drivesTitle: "ما يحفزنا", valueHeart: "بكل محبة", valueHeartDesc: "كل طبق يُحضَّر بشغف حقيقي — ليس وجبات سريعة بل طبخ حقيقي.", valueFresh: "مكونات طازجة", valueFreshDesc: "نستخدم مكونات طازجة وعالية الجودة كل يوم — بلا تنازل.", valueFamily: "عائلي", valueFamilyDesc: "كمشروع عائلي، الدفء والضيافة تأتي أولاً.", valueLocal: "محلي الجذور", valueLocalDesc: "في قلب شفيبيش غموند — جارك للمأكولات الآسيوية.", hoursTag: "دائماً لخدمتك", hoursTitle: "ساعات العمل", addressTag: "زرنا", addressTitle: "العنوان", mondayFriday: "الاثنين – الجمعة", saturdayHours: "السبت", sundayClosed: "مغلق" },
    contact: { title: "اتصل بنا", subtitle: "راسلنا", reachTitle: "كيف تتواصل معنا", phoneLabel: "هاتف", phoneHint: "أسرع طريقة هي الهاتف", addressLabel: "العنوان", hoursLabel: "ساعات العمل", hoursMoSa: "الاثنين–السبت: 11:00–20:30", hoursSun: "الأحد مغلق", mapsBtn: "افتح في خرائط جوجل", msgTitle: "أرسل رسالة", thankYouTitle: "شكراً على رسالتك!", thankYouDesc: "سنرد عليك في أقرب وقت.", nameLabel: "الاسم", namePlaceholder: "محمد أحمد", emailLabel: "البريد الإلكتروني", emailPlaceholder: "بريدك@email.com", msgLabel: "الرسالة", msgPlaceholder: "كيف يمكننا مساعدتك؟", sendBtn: "إرسال الرسالة" },
    careers: { title: "وظائف", subtitle: "انضم إلى فريقنا" },
    checkout: { title: "الدفع", backToOrder: "العودة للطلب", yourDetails: "بياناتك", nameLabel: "الاسم *", phoneLabelReq: "الهاتف *", emailLabel: "البريد الإلكتروني", notesLabel: "ملاحظات الطلب", notesPlaceholder: "مثل: بدون حار، صلصة إضافية…", pickupOrDelivery: "استلام أو توصيل", pickup: "🏪 استلام", delivery: "🛵 توصيل (+2,00 €)", streetPlaceholder: "الشارع والرقم", zipPlaceholder: "الرمز البريدي", cityPlaceholder: "المدينة", payment: "الدفع", continueBtn: "المتابعة للدفع", editDetails: "تعديل البيانات", securePayment: "دفع آمن", orderSummary: "الطلب", subtotal: "المجموع الجزئي", deliveryFee: "رسوم التوصيل", total: "المجموع الكلي", sslNote: "دفع مشفر SSL", thankYou: "شكراً جزيلاً!", thankYouMsg: "تم تقديم طلبك بنجاح", thankYouPhone: "سنتصل للتأكيد.", backHome: "العودة للرئيسية", cartEmpty: "سلتك فارغة.", cartEmptyLink: "العودة للطلب", loading: "جاري التحميل…" },
    footer: { tagline: "مطبخ آسيوي أصيل في شفيبيش غموند.", rights: "جميع الحقوق محفوظة." },
  },

  zh: {
    langName: "中文", flag: "🇨🇳", dir: "ltr",
    nav: { home: "首页", menu: "菜单", order: "点餐", about: "关于我们", contact: "联系我们", careers: "招聘" },
    common: { orderNow: "立即点餐", viewMenu: "查看菜单", viewFullMenu: "完整菜单", learnMore: "了解更多", phone: "电话", address: "地址", openingHours: "营业时间", closed: "休息", monday: "周一", saturday: "周六", sunday: "周日" },
    home: { heroDesc: "正宗亚洲美食 — 从酥脆的春卷、炒饭到香浓的泰式咖喱。每日新鲜制作，用心呈现。", categoriesTitle: "我们的特色", noodleBox: "面条盒", noodleBoxDesc: "炒面或炒饭，每日新鲜制作", curry: "泰式咖喱", curryDesc: "浓郁椰奶，新鲜香草", springRolls: "春卷", springRollsDesc: "酥脆油炸，自制酱汁", freshTitle: "每日新鲜食材，精心烹制", freshDesc: "我们每天使用新鲜蔬菜、优质肉类和精选香料 — 品质无妥协。", testimonialsTitle: "顾客评价", testimonialQuote: "\"Schwäbisch Gmünd最好的亚洲餐厅！面条盒真的无与伦比 — 新鲜、美味、每次都完美。\"", testimonialAuthor: "— Maria S.，忠实顾客", ctaTitle: "想吃亚洲菜了？", ctaDesc: "立即在线点餐，或到Ledergasse 44–46来找我们。", ctaBtn: "在线点餐" },
    menu: { title: "菜单", subtitle: "每日新鲜制作。" },
    order: { title: "点餐", subtitle: "选好菜品后，我们会电话确认。", phoneDirect: "直接来电:", cartTitle: "购物车", cartEmpty: "购物车是空的", cartEmptyHint: "请选择菜品", total: "合计", checkout: "去结账", phoneAlt: "更喜欢电话订餐？", small: "小份", large: "大份", addToCart: "加入", sauceNote: "含酱汁：酱油、甜酸汁或泰式椰奶咖喱" },
    about: { title: "关于我们", subtitle: "Schwäbisch Gmünd中心地带的正宗亚洲美食。", storyTag: "我们的故事", whoTag: "我们是谁", whoTitle: "对美味的热情", whoDesc: "LYS Noodle Box代表着充满心意的正宗亚洲美食。", drivesTag: "我们的动力", drivesTitle: "我们的动力", valueHeart: "用心烹制", valueHeartDesc: "每道菜都充满真诚的热情与用心 — 不是快餐，而是真正的厨艺。", valueFresh: "新鲜食材", valueFreshDesc: "我们每天使用新鲜、高品质的食材 — 绝不妥协。", valueFamily: "家庭经营", valueFamilyDesc: "作为家庭企业，温暖与热情款待始终第一。", valueLocal: "扎根本地", valueLocalDesc: "位于Schwäbisch Gmünd中心 — 您身边的亚洲美食邻居。", hoursTag: "随时为您服务", hoursTitle: "营业时间", addressTag: "找到我们", addressTitle: "地址", mondayFriday: "周一至周五", saturdayHours: "周六", sundayClosed: "休息" },
    contact: { title: "联系我们", subtitle: "给我们留言", reachTitle: "如何联系我们", phoneLabel: "电话", phoneHint: "最快的联系方式是电话", addressLabel: "地址", hoursLabel: "营业时间", hoursMoSa: "周一至周六: 11:00–20:30", hoursSun: "周日休息", mapsBtn: "在Google Maps中打开", msgTitle: "发送消息", thankYouTitle: "感谢您的留言！", thankYouDesc: "我们将尽快与您联系。", nameLabel: "姓名", namePlaceholder: "张三", emailLabel: "电子邮件", emailPlaceholder: "您的@邮箱.com", msgLabel: "留言", msgPlaceholder: "我们能为您做什么？", sendBtn: "发送消息" },
    careers: { title: "招聘", subtitle: "加入我们的团队" },
    checkout: { title: "结账", backToOrder: "返回点餐", yourDetails: "您的信息", nameLabel: "姓名 *", phoneLabelReq: "电话 *", emailLabel: "电子邮件", notesLabel: "订单备注", notesPlaceholder: "例如: 不要辣，额外酱汁…", pickupOrDelivery: "自取或配送", pickup: "🏪 自取", delivery: "🛵 配送 (+2,00 €)", streetPlaceholder: "街道和门牌号", zipPlaceholder: "邮政编码", cityPlaceholder: "城市", payment: "支付", continueBtn: "继续支付", editDetails: "修改信息", securePayment: "安全支付", orderSummary: "订单", subtotal: "小计", deliveryFee: "配送费", total: "合计", sslNote: "SSL加密支付", thankYou: "非常感谢！", thankYouMsg: "您的订单已成功提交", thankYouPhone: "我们将来电确认。", backHome: "返回首页", cartEmpty: "您的购物车是空的。", cartEmptyLink: "返回点餐", loading: "加载中…" },
    footer: { tagline: "Schwäbisch Gmünd正宗亚洲美食。", rights: "保留所有权利。" },
  },

  ja: {
    langName: "日本語", flag: "🇯🇵", dir: "ltr",
    nav: { home: "ホーム", menu: "メニュー", order: "注文", about: "私たちについて", contact: "お問い合わせ", careers: "採用情報" },
    common: { orderNow: "今すぐ注文", viewMenu: "メニューを見る", viewFullMenu: "全メニュー", learnMore: "詳しく見る", phone: "電話", address: "住所", openingHours: "営業時間", closed: "定休日", monday: "月曜日", saturday: "土曜日", sunday: "日曜日" },
    home: { heroDesc: "本格アジア料理 — パリパリの春巻き、チャーハンから香り豊かなタイカレーまで。毎日新鮮に作り、愛情を込めてお届けします。", categoriesTitle: "私たちの特徴", noodleBox: "ヌードルボックス", noodleBoxDesc: "炒め麺またはチャーハン、毎日新鮮に", curry: "タイカレー", curryDesc: "クリーミーなココナッツミルク、新鮮なハーブ", springRolls: "春巻き", springRollsDesc: "カリカリ揚げ、自家製ソース", freshTitle: "毎日新鮮な食材で作ります", freshDesc: "新鮮な野菜、高品質な肉、厳選されたスパイスを毎日使用 — 品質に妥協しません。", testimonialsTitle: "お客様の声", testimonialQuote: "「シュヴェービッシュ・グミュントで最高のアジア料理店！ヌードルボックスは本当に絶品です。」", testimonialAuthor: "— Maria S.、常連のお客様", ctaTitle: "アジア料理が食べたくなりましたか？", ctaDesc: "今すぐオンライン注文、またはLedergasse 44–46にお越しください。", ctaBtn: "オンラインで注文" },
    menu: { title: "メニュー", subtitle: "毎日新鮮に作っています。" },
    order: { title: "注文", subtitle: "料理を選んでいただくと、電話で確認します。", phoneDirect: "直接電話:", cartTitle: "カート", cartEmpty: "カートは空です", cartEmptyHint: "料理を選択してください", total: "合計", checkout: "レジへ", phoneAlt: "電話で注文しますか？", small: "小", large: "大", addToCart: "追加", sauceNote: "ソース付き: 醤油、甘酢、またはタイカレーとコcoナッツミルク" },
    about: { title: "私たちについて", subtitle: "シュヴェービッシュ・グミュントの中心にある本格アジア料理。", storyTag: "私たちのストーリー", whoTag: "私たちについて", whoTitle: "味への情熱", whoDesc: "LYS Noodle Boxは心を込めた本格アジア料理を提供します。", drivesTag: "私たちの原動力", drivesTitle: "私たちの原動力", valueHeart: "心を込めて", valueHeartDesc: "すべての料理に本物の情熱とこだわりを込めて — ファストフードではなく本物の料理。", valueFresh: "新鮮な食材", valueFreshDesc: "毎日新鮮で高品質な食材を使用 — 妥協なし。", valueFamily: "家族経営", valueFamilyDesc: "家族経営として、温かさとおもてなしを最優先に。", valueLocal: "地域に根付いて", valueLocalDesc: "シュヴェービッシュ・グミュントの中心 — アジア料理のご近所さん。", hoursTag: "いつでもお待ちしています", hoursTitle: "営業時間", addressTag: "場所の確認", addressTitle: "住所", mondayFriday: "月曜日 – 金曜日", saturdayHours: "土曜日", sundayClosed: "定休日" },
    contact: { title: "お問い合わせ", subtitle: "メッセージを送る", reachTitle: "連絡方法", phoneLabel: "電話", phoneHint: "最も速い連絡方法は電話です", addressLabel: "住所", hoursLabel: "営業時間", hoursMoSa: "月〜土: 11:00〜20:30", hoursSun: "日曜定休", mapsBtn: "Google Mapsで開く", msgTitle: "メッセージを送る", thankYouTitle: "メッセージありがとうございます！", thankYouDesc: "できるだけ早くご連絡いたします。", nameLabel: "お名前", namePlaceholder: "山田 太郎", emailLabel: "メールアドレス", emailPlaceholder: "your@email.jp", msgLabel: "メッセージ", msgPlaceholder: "どのようなお手伝いができますか？", sendBtn: "送信" },
    careers: { title: "採用情報", subtitle: "私たちのチームに参加しませんか" },
    checkout: { title: "レジ", backToOrder: "注文に戻る", yourDetails: "お客様情報", nameLabel: "お名前 *", phoneLabelReq: "電話番号 *", emailLabel: "メールアドレス", notesLabel: "注文のメモ", notesPlaceholder: "例: 辛さなし、追加ソース…", pickupOrDelivery: "受け取りまたは配達", pickup: "🏪 受け取り", delivery: "🛵 配達 (+2.00 €)", streetPlaceholder: "番地", zipPlaceholder: "郵便番号", cityPlaceholder: "市区町村", payment: "お支払い", continueBtn: "お支払いへ", editDetails: "情報を編集", securePayment: "安全なお支払い", orderSummary: "注文内容", subtotal: "小計", deliveryFee: "配達料", total: "合計", sslNote: "SSL暗号化決済", thankYou: "ありがとうございます！", thankYouMsg: "ご注文が正常に完了しました", thankYouPhone: "電話にて確認のご連絡をいたします。", backHome: "ホームに戻る", cartEmpty: "カートが空です。", cartEmptyLink: "注文に戻る", loading: "読み込み中…" },
    footer: { tagline: "シュヴェービッシュ・グミュントの本格アジア料理。", rights: "全著作権所有。" },
  },

  ko: {
    langName: "한국어", flag: "🇰🇷", dir: "ltr",
    nav: { home: "홈", menu: "메뉴", order: "주문", about: "소개", contact: "연락처", careers: "채용" },
    common: { orderNow: "지금 주문하기", viewMenu: "메뉴 보기", viewFullMenu: "전체 메뉴", learnMore: "더 알아보기", phone: "전화", address: "주소", openingHours: "영업시간", closed: "휴무", monday: "월요일", saturday: "토요일", sunday: "일요일" },
    home: { heroDesc: "정통 아시아 요리 — 바삭한 스프링롤부터 볶음밥, 향긋한 태국 카레까지. 매일 신선하게 조리해 사랑을 담아 드립니다.", categoriesTitle: "우리의 특별함", noodleBox: "누들 박스", noodleBoxDesc: "볶음면 또는 볶음밥, 매일 신선하게", curry: "태국 카레", curryDesc: "크리미한 코코넛 밀크, 신선한 허브", springRolls: "스프링롤", springRollsDesc: "바삭하게 튀긴, 수제 소스", freshTitle: "신선한 재료, 매일 조리", freshDesc: "매일 신선한 채소, 고품질 육류, 엄선된 향신료를 사용합니다 — 품질에 타협 없음.", testimonialsTitle: "고객 후기", testimonialQuote: "\"슈베비슈 그뮌트 최고의 아시아 레스토랑! 누들 박스는 정말 최고입니다.\"", testimonialAuthor: "— Maria S., 단골 고객", ctaTitle: "아시아 음식이 당기시나요?", ctaDesc: "지금 온라인 주문하거나 Ledergasse 44–46로 방문해 주세요.", ctaBtn: "온라인 주문" },
    menu: { title: "메뉴", subtitle: "매일 신선하게 조리합니다." },
    order: { title: "주문", subtitle: "메뉴를 선택하면 확인 전화를 드립니다.", phoneDirect: "직접 전화:", cartTitle: "장바구니", cartEmpty: "장바구니가 비어 있습니다", cartEmptyHint: "메뉴를 선택해 주세요", total: "합계", checkout: "결제하기", phoneAlt: "전화로 주문하시겠어요?", small: "소", large: "대", addToCart: "추가", sauceNote: "소스 포함: 간장, 새콤달콤, 또는 코코넛 밀크 태국 카레" },
    about: { title: "소개", subtitle: "슈베비슈 그뮌트 중심의 정통 아시아 요리.", storyTag: "우리의 이야기", whoTag: "우리는 누구인가", whoTitle: "맛에 대한 열정", whoDesc: "LYS Noodle Box는 진심을 담은 정통 아시아 요리를 선보입니다.", drivesTag: "우리의 원동력", drivesTitle: "우리의 원동력", valueHeart: "진심으로", valueHeartDesc: "모든 음식은 진정한 열정과 정성으로 조리됩니다 — 패스트푸드가 아닌 진짜 요리.", valueFresh: "신선한 재료", valueFreshDesc: "매일 신선하고 고품질의 재료를 사용합니다 — 타협 없음.", valueFamily: "가족 경영", valueFamilyDesc: "가족 기업으로서 따뜻함과 개인적인 환대를 최우선으로.", valueLocal: "지역 뿌리", valueLocalDesc: "슈베비슈 그뮌트 중심 — 아시아 요리를 위한 이웃.", hoursTag: "항상 여러분을 위해", hoursTitle: "영업시간", addressTag: "찾아오세요", addressTitle: "주소", mondayFriday: "월요일 – 금요일", saturdayHours: "토요일", sundayClosed: "휴무" },
    contact: { title: "연락처", subtitle: "메시지 보내기", reachTitle: "연락 방법", phoneLabel: "전화", phoneHint: "가장 빠른 연락 방법은 전화입니다", addressLabel: "주소", hoursLabel: "영업시간", hoursMoSa: "월–토: 11:00–20:30", hoursSun: "일요일 휴무", mapsBtn: "Google Maps에서 열기", msgTitle: "메시지 보내기", thankYouTitle: "메시지 감사합니다!", thankYouDesc: "최대한 빨리 연락드리겠습니다.", nameLabel: "이름", namePlaceholder: "홍길동", emailLabel: "이메일", emailPlaceholder: "your@email.kr", msgLabel: "메시지", msgPlaceholder: "어떻게 도와드릴까요?", sendBtn: "메시지 보내기" },
    careers: { title: "채용", subtitle: "우리 팀에 합류하세요" },
    checkout: { title: "결제", backToOrder: "주문으로 돌아가기", yourDetails: "고객 정보", nameLabel: "이름 *", phoneLabelReq: "전화번호 *", emailLabel: "이메일", notesLabel: "주문 메모", notesPlaceholder: "예: 맵지 않게, 소스 추가…", pickupOrDelivery: "픽업 또는 배달", pickup: "🏪 픽업", delivery: "🛵 배달 (+2.00 €)", streetPlaceholder: "도로명 주소", zipPlaceholder: "우편번호", cityPlaceholder: "도시", payment: "결제", continueBtn: "결제 계속", editDetails: "정보 수정", securePayment: "안전한 결제", orderSummary: "주문 내역", subtotal: "소계", deliveryFee: "배달비", total: "합계", sslNote: "SSL 암호화 결제", thankYou: "감사합니다!", thankYouMsg: "주문이 성공적으로 접수되었습니다", thankYouPhone: "확인을 위해 전화드리겠습니다.", backHome: "홈으로 돌아가기", cartEmpty: "장바구니가 비어 있습니다.", cartEmptyLink: "주문으로 돌아가기", loading: "로딩 중…" },
    footer: { tagline: "슈베비슈 그뮌트의 정통 아시아 요리.", rights: "모든 권리 보유." },
  },

  nl: {
    langName: "Nederlands", flag: "🇳🇱", dir: "ltr",
    nav: { home: "Home", menu: "Menu", order: "Bestellen", about: "Over ons", contact: "Contact", careers: "Vacatures" },
    common: { orderNow: "Nu bestellen", viewMenu: "Menu bekijken", viewFullMenu: "Volledig menu", learnMore: "Meer info", phone: "Telefoon", address: "Adres", openingHours: "Openingstijden", closed: "Gesloten", monday: "Maandag", saturday: "Zaterdag", sunday: "Zondag" },
    home: { heroDesc: "Authentieke Aziatische keuken — van knapperige loempia's en gebakken rijst tot aromatische Thaise curry's. Dagelijks vers bereid, met liefde geserveerd.", categoriesTitle: "Wat ons bijzonder maakt", noodleBox: "Noodle Box", noodleBoxDesc: "Gebakken noedels of rijst, dagelijks vers", curry: "Thaise Curry", curryDesc: "Romige kokosmelk, verse kruiden", springRolls: "Loempia's", springRollsDesc: "Knapperig gebakken, huisgemaakte saus", freshTitle: "Verse ingrediënten, dagelijks bereid", freshDesc: "We gebruiken elke dag verse groenten, hoogwaardig vlees en uitgekozen kruiden — geen compromis.", testimonialsTitle: "Wat onze gasten zeggen", testimonialQuote: "\"Het beste Aziatische restaurant in Schwäbisch Gmünd! De Noodle Box is gewoonweg onverslaanbaar.\"", testimonialAuthor: "— Maria S., trouwe klant", ctaTitle: "Zin in Aziatisch eten?", ctaDesc: "Bestel nu online of bezoek ons in Ledergasse 44–46.", ctaBtn: "Online bestellen" },
    menu: { title: "Menu", subtitle: "Dagelijks vers bereid." },
    order: { title: "Bestellen", subtitle: "Kies uw gerechten en wij bellen voor bevestiging.", phoneDirect: "Bel direct:", cartTitle: "Winkelwagen", cartEmpty: "Winkelwagen is leeg", cartEmptyHint: "Selecteer gerechten", total: "Totaal", checkout: "Afrekenen", phoneAlt: "Liever telefonisch bestellen?", small: "Klein", large: "Groot", addToCart: "Toevoegen", sauceNote: "Incl. saus: soja, zoetzuur of Thaise curry met kokosmelk" },
    about: { title: "Over ons", subtitle: "Authentieke Aziatische keuken in het hart van Schwäbisch Gmünd.", storyTag: "Ons verhaal", whoTag: "Wie we zijn", whoTitle: "Passie voor smaak", whoDesc: "LYS Noodle Box staat voor authentieke Aziatische keuken met hart.", drivesTag: "Wat ons drijft", drivesTitle: "Wat ons drijft", valueHeart: "Met hart", valueHeartDesc: "Elk gerecht wordt met echte passie bereid — geen fastfood, maar echte keuken.", valueFresh: "Verse ingrediënten", valueFreshDesc: "We gebruiken elke dag verse, hoogwaardige ingrediënten — geen compromissen.", valueFamily: "Familiebedrijf", valueFamilyDesc: "Als familiebedrijf staan warmte en gastvrijheid voorop.", valueLocal: "Lokaal verankerd", valueLocalDesc: "In het hart van Schwäbisch Gmünd — uw buur voor Aziatische specialiteiten.", hoursTag: "Altijd voor u beschikbaar", hoursTitle: "Openingstijden", addressTag: "Vind ons", addressTitle: "Adres", mondayFriday: "Maandag – Vrijdag", saturdayHours: "Zaterdag", sundayClosed: "Gesloten" },
    contact: { title: "Contact", subtitle: "Schrijf ons", reachTitle: "Hoe u ons kunt bereiken", phoneLabel: "Telefoon", phoneHint: "De snelste manier is per telefoon", addressLabel: "Adres", hoursLabel: "Openingstijden", hoursMoSa: "Ma–Za: 11:00–20:30", hoursSun: "Zondag gesloten", mapsBtn: "Openen in Google Maps", msgTitle: "Bericht sturen", thankYouTitle: "Bedankt voor uw bericht!", thankYouDesc: "We reageren zo snel mogelijk.", nameLabel: "Naam", namePlaceholder: "Jan de Vries", emailLabel: "E-mail", emailPlaceholder: "uw@email.nl", msgLabel: "Bericht", msgPlaceholder: "Hoe kunnen we u helpen?", sendBtn: "Bericht versturen" },
    careers: { title: "Vacatures", subtitle: "Word lid van ons team" },
    checkout: { title: "Afrekenen", backToOrder: "Terug naar bestelling", yourDetails: "Uw gegevens", nameLabel: "Naam *", phoneLabelReq: "Telefoon *", emailLabel: "E-mail", notesLabel: "Opmerkingen bij bestelling", notesPlaceholder: "bijv. niet pittig, extra saus…", pickupOrDelivery: "Afhalen of bezorging", pickup: "🏪 Afhalen", delivery: "🛵 Bezorging (+2,00 €)", streetPlaceholder: "Straat en huisnummer", zipPlaceholder: "Postcode", cityPlaceholder: "Stad", payment: "Betaling", continueBtn: "Doorgaan naar betaling", editDetails: "Gegevens bewerken", securePayment: "Veilige betaling", orderSummary: "Bestelling", subtotal: "Subtotaal", deliveryFee: "Bezorgkosten", total: "Totaal", sslNote: "SSL-versleutelde betaling", thankYou: "Hartelijk dank!", thankYouMsg: "Uw bestelling is succesvol geplaatst", thankYouPhone: "We bellen voor bevestiging.", backHome: "Terug naar homepage", cartEmpty: "Uw winkelwagen is leeg.", cartEmptyLink: "Terug naar bestelling", loading: "Laden…" },
    footer: { tagline: "Authentieke Aziatische keuken in Schwäbisch Gmünd.", rights: "Alle rechten voorbehouden." },
  },

  ro: {
    langName: "Română", flag: "🇷🇴", dir: "ltr",
    nav: { home: "Acasă", menu: "Meniu", order: "Comandă", about: "Despre noi", contact: "Contact", careers: "Cariere" },
    common: { orderNow: "Comandă acum", viewMenu: "Vezi meniu", viewFullMenu: "Meniu complet", learnMore: "Află mai mult", phone: "Telefon", address: "Adresă", openingHours: "Program", closed: "Închis", monday: "Luni", saturday: "Sâmbătă", sunday: "Duminică" },
    home: { heroDesc: "Bucătărie asiatică autentică — de la rulourile de primăvară crocante la orez prăjit și curry-uri tailandeze aromate. Proaspăt pregătit, servit cu dragoste.", categoriesTitle: "Ce ne face speciali", noodleBox: "Noodle Box", noodleBoxDesc: "Tăiței sau orez prăjiți, proaspăt preparați", curry: "Curry Tailandez", curryDesc: "Lapte de cocos cremos, ierburi proaspete", springRolls: "Rulouri de Primăvară", springRollsDesc: "Prăjite crocant, sos de casă", freshTitle: "Ingrediente proaspete, preparate zilnic", freshDesc: "Folosim zilnic legume proaspete, carne de calitate și condimente alese — fără compromisuri.", testimonialsTitle: "Ce spun oaspeții noștri", testimonialQuote: "\"Cel mai bun restaurant asiatic din Schwäbisch Gmünd! Noodle Box este pur și simplu de neîntrecut.\"", testimonialAuthor: "— Maria S., clientă fidelă", ctaTitle: "Îți e poftă de mâncare asiatică?", ctaDesc: "Comandă online sau vizitează-ne la Ledergasse 44–46.", ctaBtn: "Comandă online" },
    menu: { title: "Meniu", subtitle: "Preparat proaspăt — în fiecare zi." },
    order: { title: "Comandă", subtitle: "Alege preparatele și te sunăm pentru confirmare.", phoneDirect: "Sunați direct:", cartTitle: "Coș", cartEmpty: "Coșul este gol", cartEmptyHint: "Selectați preparate", total: "Total", checkout: "La casă", phoneAlt: "Preferați să comandați telefonic?", small: "Mic", large: "Mare", addToCart: "Adaugă", sauceNote: "Incl. sos: soia, acru-dulce sau curry tailandez cu lapte de cocos" },
    about: { title: "Despre noi", subtitle: "Bucătărie asiatică autentică în inima Schwäbisch Gmünd.", storyTag: "Povestea noastră", whoTag: "Cine suntem", whoTitle: "Pasiune pentru gust", whoDesc: "LYS Noodle Box reprezintă bucătăria asiatică autentică din inimă.", drivesTag: "Ce ne motivează", drivesTitle: "Ce ne motivează", valueHeart: "Cu inimă", valueHeartDesc: "Fiecare preparat este gătit cu adevărată pasiune — nu fast-food, ci gătit adevărat.", valueFresh: "Ingrediente proaspete", valueFreshDesc: "Folosim ingrediente proaspete, de calitate în fiecare zi — fără compromisuri.", valueFamily: "Familie", valueFamilyDesc: "Ca afacere de familie, căldura și ospitalitatea sunt pe primul loc.", valueLocal: "Înrădăcinați local", valueLocalDesc: "În inima Schwäbisch Gmünd — vecinul tău pentru specialități asiatice.", hoursTag: "Mereu pentru tine", hoursTitle: "Program de funcționare", addressTag: "Găsește-ne", addressTitle: "Adresă", mondayFriday: "Luni – Vineri", saturdayHours: "Sâmbătă", sundayClosed: "Închis" },
    contact: { title: "Contact", subtitle: "Scrie-ne", reachTitle: "Cum să ne contactezi", phoneLabel: "Telefon", phoneHint: "Cel mai rapid mod este prin telefon", addressLabel: "Adresă", hoursLabel: "Program", hoursMoSa: "Lun–Sâm: 11:00–20:30", hoursSun: "Duminică închis", mapsBtn: "Deschide în Google Maps", msgTitle: "Trimite un mesaj", thankYouTitle: "Mulțumim pentru mesaj!", thankYouDesc: "Îți vom răspunde cât mai curând.", nameLabel: "Nume", namePlaceholder: "Ion Popescu", emailLabel: "Email", emailPlaceholder: "al.tau@email.ro", msgLabel: "Mesaj", msgPlaceholder: "Cum te putem ajuta?", sendBtn: "Trimite mesajul" },
    careers: { title: "Cariere", subtitle: "Alătură-te echipei noastre" },
    checkout: { title: "Casă", backToOrder: "Înapoi la comandă", yourDetails: "Datele tale", nameLabel: "Nume *", phoneLabelReq: "Telefon *", emailLabel: "Email", notesLabel: "Note comandă", notesPlaceholder: "ex. fără condimente, sos suplimentar…", pickupOrDelivery: "Ridicare sau livrare", pickup: "🏪 Ridicare", delivery: "🛵 Livrare (+2,00 €)", streetPlaceholder: "Stradă și număr", zipPlaceholder: "Cod poștal", cityPlaceholder: "Oraș", payment: "Plată", continueBtn: "Continuă spre plată", editDetails: "Editează datele", securePayment: "Plată securizată", orderSummary: "Comandă", subtotal: "Subtotal", deliveryFee: "Cost livrare", total: "Total", sslNote: "Plată criptată SSL", thankYou: "Mulțumim foarte mult!", thankYouMsg: "Comanda ta a fost plasată cu succes", thankYouPhone: "Te vom suna pentru confirmare.", backHome: "Înapoi acasă", cartEmpty: "Coșul tău este gol.", cartEmptyLink: "Înapoi la comandă", loading: "Se încarcă…" },
    footer: { tagline: "Bucătărie asiatică autentică în Schwäbisch Gmünd.", rights: "Toate drepturile rezervate." },
  },

  hu: {
    langName: "Magyar", flag: "🇭🇺", dir: "ltr",
    nav: { home: "Főoldal", menu: "Menü", order: "Rendelés", about: "Rólunk", contact: "Kapcsolat", careers: "Karrier" },
    common: { orderNow: "Rendeléje most", viewMenu: "Menü megtekintése", viewFullMenu: "Teljes menü", learnMore: "Tudj meg többet", phone: "Telefon", address: "Cím", openingHours: "Nyitvatartás", closed: "Zárva", monday: "Hétfő", saturday: "Szombat", sunday: "Vasárnap" },
    home: { heroDesc: "Hiteles ázsiai konyha — ropogós tavaszi tekercsektől a sült rizsen át az aromás thai currykig. Minden nap frissen készítve, szeretettel tálalva.", categoriesTitle: "Ami különlegessé tesz minket", noodleBox: "Noodle Box", noodleBoxDesc: "Sült tészta vagy rizs, frissen elkészítve", curry: "Thai Curry", curryDesc: "Krémes kókusztej, friss fűszerek", springRolls: "Tavaszi Tekercs", springRollsDesc: "Ropogósra sütve, házi szósszal", freshTitle: "Friss alapanyagok, naponta elkészítve", freshDesc: "Minden nap friss zöldséget, minőségi húst és válogatott fűszereket használunk — kompromisszum nélkül.", testimonialsTitle: "Vendégeink véleménye", testimonialQuote: "\"A legjobb ázsiai étterem Schwäbisch Gmündben! A Noodle Box egyszerűen verhetetlen.\"", testimonialAuthor: "— Maria S., hűséges törzsvendég", ctaTitle: "Megkívánta az ázsiai ételt?", ctaDesc: "Rendelje online vagy látogasson el hozzánk a Ledergasse 44–46 alá.", ctaBtn: "Online rendelés" },
    menu: { title: "Menü", subtitle: "Naponta frissen elkészítve." },
    order: { title: "Rendelés", subtitle: "Válassza ki fogásait, és telefonon visszaigazoljuk.", phoneDirect: "Hívjon közvetlenül:", cartTitle: "Kosár", cartEmpty: "A kosár üres", cartEmptyHint: "Válasszon fogásokat", total: "Összesen", checkout: "Pénztárhoz", phoneAlt: "Inkább telefonon rendel?", small: "Kis", large: "Nagy", addToCart: "Hozzáad", sauceNote: "Szósz mellékelve: szója, édes-savanyú vagy thai curry kókusztejjel" },
    about: { title: "Rólunk", subtitle: "Hiteles ázsiai konyha Schwäbisch Gmünd szívében.", storyTag: "A mi történetünk", whoTag: "Kik vagyunk", whoTitle: "Szenvedély az ízért", whoDesc: "A LYS Noodle Box szívből jövő hiteles ázsiai konyhát képvisel.", drivesTag: "Mi hajt minket", drivesTitle: "Mi hajt minket", valueHeart: "Szívből", valueHeartDesc: "Minden ételt valódi szenvedéllyel és gondossággal készítünk — nem gyorsétterem, hanem igazi konyha.", valueFresh: "Friss alapanyagok", valueFreshDesc: "Minden nap friss, kiváló minőségű alapanyagokat használunk — kompromisszum nélkül.", valueFamily: "Családias", valueFamilyDesc: "Családi vállalkozásként a melegség és a személyes vendéglátás az első.", valueLocal: "Helyileg gyökerező", valueLocalDesc: "Schwäbisch Gmünd szívében — az ázsiai specialitások szomszédja.", hoursTag: "Mindig az Ön rendelkezésére", hoursTitle: "Nyitvatartás", addressTag: "Találjon meg minket", addressTitle: "Cím", mondayFriday: "Hétfő – Péntek", saturdayHours: "Szombat", sundayClosed: "Zárva" },
    contact: { title: "Kapcsolat", subtitle: "Írjon nekünk", reachTitle: "Hogyan érhet el minket", phoneLabel: "Telefon", phoneHint: "A leggyorsabb módja a telefonálás", addressLabel: "Cím", hoursLabel: "Nyitvatartás", hoursMoSa: "H–Szo: 11:00–20:30", hoursSun: "Vasárnap zárva", mapsBtn: "Megnyitás Google Térképen", msgTitle: "Üzenet küldése", thankYouTitle: "Köszönjük az üzenetét!", thankYouDesc: "Mielőbb visszajelzünk.", nameLabel: "Név", namePlaceholder: "Kovács János", emailLabel: "E-mail", emailPlaceholder: "az.ön@email.hu", msgLabel: "Üzenet", msgPlaceholder: "Miben segíthetünk?", sendBtn: "Üzenet küldése" },
    careers: { title: "Karrier", subtitle: "Csatlakozzon csapatunkhoz" },
    checkout: { title: "Pénztár", backToOrder: "Vissza a rendeléshez", yourDetails: "Az Ön adatai", nameLabel: "Név *", phoneLabelReq: "Telefon *", emailLabel: "E-mail", notesLabel: "Megjegyzések a rendeléshez", notesPlaceholder: "pl. ne legyen csípős, extra szósz…", pickupOrDelivery: "Átvétel vagy kiszállítás", pickup: "🏪 Átvétel", delivery: "🛵 Kiszállítás (+2,00 €)", streetPlaceholder: "Utca és házszám", zipPlaceholder: "Irányítószám", cityPlaceholder: "Város", payment: "Fizetés", continueBtn: "Tovább a fizetéshez", editDetails: "Adatok szerkesztése", securePayment: "Biztonságos fizetés", orderSummary: "Rendelés", subtotal: "Részösszeg", deliveryFee: "Kiszállítási díj", total: "Összesen", sslNote: "SSL-titkosított fizetés", thankYou: "Köszönjük szépen!", thankYouMsg: "Rendelése sikeresen leadva", thankYouPhone: "Telefonon visszaigazoljuk.", backHome: "Vissza a főoldalra", cartEmpty: "A kosara üres.", cartEmptyLink: "Vissza a rendeléshez", loading: "Betöltés…" },
    footer: { tagline: "Hiteles ázsiai konyha Schwäbisch Gmündben.", rights: "Minden jog fenntartva." },
  },

  cs: {
    langName: "Čeština", flag: "🇨🇿", dir: "ltr",
    nav: { home: "Domů", menu: "Jídelní lístek", order: "Objednat", about: "O nás", contact: "Kontakt", careers: "Kariéra" },
    common: { orderNow: "Objednat nyní", viewMenu: "Zobrazit menu", viewFullMenu: "Kompletní menu", learnMore: "Zjistit více", phone: "Telefon", address: "Adresa", openingHours: "Otevírací doba", closed: "Zavřeno", monday: "Pondělí", saturday: "Sobota", sunday: "Neděle" },
    home: { heroDesc: "Autentická asijská kuchyně — od křupavých jarních závitků přes smažené rýže až po aromatické thajské kari. Každý den čerstvě připraveno, podáváno s láskou.", categoriesTitle: "Co nás dělá výjimečnými", noodleBox: "Noodle Box", noodleBoxDesc: "Smažené nudle nebo rýže, čerstvě připravené", curry: "Thajské kari", curryDesc: "Krémové kokosové mléko, čerstvé bylinky", springRolls: "Jarní závitky", springRollsDesc: "Křupavě osmažené, domácí omáčka", freshTitle: "Čerstvé ingredience, připravované denně", freshDesc: "Každý den používáme čerstvou zeleninu, kvalitní maso a vybrané koření — bez kompromisů.", testimonialsTitle: "Co říkají naši hosté", testimonialQuote: "\"Nejlepší asijská restaurace ve Schwäbisch Gmündu! Noodle Box je prostě neporazitelná.\"", testimonialAuthor: "— Maria S., věrná zákaznice", ctaTitle: "Máte chuť na asijské jídlo?", ctaDesc: "Objednejte online nebo nás navštivte na Ledergasse 44–46.", ctaBtn: "Objednat online" },
    menu: { title: "Jídelní lístek", subtitle: "Každý den čerstvě připraveno." },
    order: { title: "Objednat", subtitle: "Vyberte pokrmy a zavoláme vám pro potvrzení.", phoneDirect: "Zavolejte přímo:", cartTitle: "Košík", cartEmpty: "Košík je prázdný", cartEmptyHint: "Vyberte pokrmy", total: "Celkem", checkout: "K pokladně", phoneAlt: "Raději objednáte telefonicky?", small: "Malý", large: "Velký", addToCart: "Přidat", sauceNote: "Včetně omáčky: sójová, sladkokyselá nebo thajské kari s kokosovým mlékem" },
    about: { title: "O nás", subtitle: "Autentická asijská kuchyně v srdci Schwäbisch Gmündu.", storyTag: "Náš příběh", whoTag: "Kdo jsme", whoTitle: "Vášeň pro chuť", whoDesc: "LYS Noodle Box představuje autentickou asijskou kuchyni se srdcem.", drivesTag: "Co nás pohání", drivesTitle: "Co nás pohání", valueHeart: "Se srdcem", valueHeartDesc: "Každé jídlo je připravováno s opravdovou vášní — ne fast food, ale skutečná kuchyně.", valueFresh: "Čerstvé suroviny", valueFreshDesc: "Každý den používáme čerstvé, vysoce kvalitní suroviny — bez kompromisů.", valueFamily: "Rodinný podnik", valueFamilyDesc: "Jako rodinný podnik stavíme teplo a osobní pohostinnost na první místo.", valueLocal: "Lokálně zakořenění", valueLocalDesc: "V srdci Schwäbisch Gmündu — váš soused pro asijské speciality.", hoursTag: "Vždy pro vás", hoursTitle: "Otevírací doba", addressTag: "Najděte nás", addressTitle: "Adresa", mondayFriday: "Pondělí – Pátek", saturdayHours: "Sobota", sundayClosed: "Zavřeno" },
    contact: { title: "Kontakt", subtitle: "Napište nám", reachTitle: "Jak nás kontaktovat", phoneLabel: "Telefon", phoneHint: "Nejrychlejší způsob je telefonicky", addressLabel: "Adresa", hoursLabel: "Otevírací doba", hoursMoSa: "Po–So: 11:00–20:30", hoursSun: "Neděle zavřeno", mapsBtn: "Otevřít v Google Maps", msgTitle: "Odeslat zprávu", thankYouTitle: "Děkujeme za zprávu!", thankYouDesc: "Ozveme se co nejdříve.", nameLabel: "Jméno", namePlaceholder: "Jan Novák", emailLabel: "E-mail", emailPlaceholder: "vas@email.cz", msgLabel: "Zpráva", msgPlaceholder: "Jak vám můžeme pomoci?", sendBtn: "Odeslat zprávu" },
    careers: { title: "Kariéra", subtitle: "Přidejte se k našemu týmu" },
    checkout: { title: "Pokladna", backToOrder: "Zpět na objednávku", yourDetails: "Vaše údaje", nameLabel: "Jméno *", phoneLabelReq: "Telefon *", emailLabel: "E-mail", notesLabel: "Poznámky k objednávce", notesPlaceholder: "např. bez pálivého, extra omáčka…", pickupOrDelivery: "Vyzvednutí nebo doručení", pickup: "🏪 Vyzvednutí", delivery: "🛵 Doručení (+2,00 €)", streetPlaceholder: "Ulice a číslo", zipPlaceholder: "PSČ", cityPlaceholder: "Město", payment: "Platba", continueBtn: "Pokračovat k platbě", editDetails: "Upravit údaje", securePayment: "Bezpečná platba", orderSummary: "Objednávka", subtotal: "Mezisoučet", deliveryFee: "Poplatek za doručení", total: "Celkem", sslNote: "SSL šifrovaná platba", thankYou: "Mockrát děkujeme!", thankYouMsg: "Vaše objednávka byla úspěšně zadána", thankYouPhone: "Zavoláme pro potvrzení.", backHome: "Zpět na hlavní stránku", cartEmpty: "Váš košík je prázdný.", cartEmptyLink: "Zpět na objednávku", loading: "Načítání…" },
    footer: { tagline: "Autentická asijská kuchyně ve Schwäbisch Gmündu.", rights: "Všechna práva vyhrazena." },
  },

  el: {
    langName: "Ελληνικά", flag: "🇬🇷", dir: "ltr",
    nav: { home: "Αρχική", menu: "Μενού", order: "Παραγγελία", about: "Σχετικά", contact: "Επικοινωνία", careers: "Θέσεις εργασίας" },
    common: { orderNow: "Παραγγείλτε τώρα", viewMenu: "Δείτε το μενού", viewFullMenu: "Πλήρες μενού", learnMore: "Μάθετε περισσότερα", phone: "Τηλέφωνο", address: "Διεύθυνση", openingHours: "Ώρες λειτουργίας", closed: "Κλειστό", monday: "Δευτέρα", saturday: "Σάββατο", sunday: "Κυριακή" },
    home: { heroDesc: "Αυθεντική ασιατική κουζίνα — από τριγανητά spring rolls και τηγανητό ρύζι μέχρι αρωματικά Thai curry. Φρέσκο κάθε μέρα, σερβιρισμένο με αγάπη.", categoriesTitle: "Τι μας κάνει ξεχωριστούς", noodleBox: "Noodle Box", noodleBoxDesc: "Τηγανητά noodles ή ρύζι, φρέσκα καθημερινά", curry: "Thai Curry", curryDesc: "Κρεμώδες γάλα καρύδας, φρέσκα μυρωδικά", springRolls: "Spring Rolls", springRollsDesc: "Τριγανητά τραγανά, σπιτική σάλτσα", freshTitle: "Φρέσκα υλικά, έτοιμα κάθε μέρα", freshDesc: "Χρησιμοποιούμε φρέσκα λαχανικά, ποιοτικό κρέας και εκλεκτά μπαχαρικά καθημερινά.", testimonialsTitle: "Τι λένε οι επισκέπτες μας", testimonialQuote: "\"Το καλύτερο ασιατικό εστιατόριο στο Schwäbisch Gmünd! Το Noodle Box είναι απλά ασύγκριτο.\"", testimonialAuthor: "— Maria S., πιστή πελάτισσα", ctaTitle: "Σας πιάνει όρεξη για ασιατικό;", ctaDesc: "Παραγγείλτε online ή επισκεφθείτε μας στην Ledergasse 44–46.", ctaBtn: "Online παραγγελία" },
    menu: { title: "Μενού", subtitle: "Φρέσκο κάθε μέρα." },
    order: { title: "Παραγγελία", subtitle: "Επιλέξτε τα πιάτα σας και θα σας καλέσουμε για επιβεβαίωση.", phoneDirect: "Καλέστε απευθείας:", cartTitle: "Καλάθι", cartEmpty: "Το καλάθι είναι άδειο", cartEmptyHint: "Επιλέξτε πιάτα", total: "Σύνολο", checkout: "Ταμείο", phoneAlt: "Προτιμάτε τηλεφωνική παραγγελία;", small: "Μικρό", large: "Μεγάλο", addToCart: "Προσθήκη", sauceNote: "Περιλαμβάνει σάλτσα: σόγιας, γλυκόξινη ή Thai curry με γάλα καρύδας" },
    about: { title: "Σχετικά με εμάς", subtitle: "Αυθεντική ασιατική κουζίνα στην καρδιά του Schwäbisch Gmünd.", storyTag: "Η ιστορία μας", whoTag: "Ποιοι είμαστε", whoTitle: "Πάθος για τη γεύση", whoDesc: "Το LYS Noodle Box αντιπροσωπεύει αυθεντική ασιατική κουζίνα με καρδιά.", drivesTag: "Τι μας κινητοποιεί", drivesTitle: "Τι μας κινητοποιεί", valueHeart: "Με καρδιά", valueHeartDesc: "Κάθε πιάτο παρασκευάζεται με αληθινό πάθος — όχι fast food, αλλά αληθινή κουζίνα.", valueFresh: "Φρέσκα υλικά", valueFreshDesc: "Χρησιμοποιούμε φρέσκα, υψηλής ποιότητας υλικά κάθε μέρα — χωρίς συμβιβασμούς.", valueFamily: "Οικογενειακή επιχείρηση", valueFamilyDesc: "Ως οικογενειακή επιχείρηση, η ζεστασιά και η φιλοξενία είναι πρώτα.", valueLocal: "Τοπικά ριζωμένοι", valueLocalDesc: "Στην καρδιά του Schwäbisch Gmünd — ο γείτονάς σας για ασιατικές σπεσιαλιτέ.", hoursTag: "Πάντα εδώ για σας", hoursTitle: "Ώρες λειτουργίας", addressTag: "Βρείτε μας", addressTitle: "Διεύθυνση", mondayFriday: "Δευτέρα – Παρασκευή", saturdayHours: "Σάββατο", sundayClosed: "Κλειστό" },
    contact: { title: "Επικοινωνία", subtitle: "Γράψτε μας", reachTitle: "Πώς να επικοινωνήσετε μαζί μας", phoneLabel: "Τηλέφωνο", phoneHint: "Ο πιο γρήγορος τρόπος είναι το τηλέφωνο", addressLabel: "Διεύθυνση", hoursLabel: "Ώρες λειτουργίας", hoursMoSa: "Δε–Σα: 11:00–20:30", hoursSun: "Κυριακή κλειστό", mapsBtn: "Άνοιγμα στο Google Maps", msgTitle: "Αποστολή μηνύματος", thankYouTitle: "Ευχαριστούμε για το μήνυμά σας!", thankYouDesc: "Θα επικοινωνήσουμε μαζί σας το συντομότερο.", nameLabel: "Όνομα", namePlaceholder: "Γιώργης Παπαδόπουλος", emailLabel: "Email", emailPlaceholder: "to@email.gr", msgLabel: "Μήνυμα", msgPlaceholder: "Πώς μπορούμε να σας βοηθήσουμε;", sendBtn: "Αποστολή μηνύματος" },
    careers: { title: "Θέσεις εργασίας", subtitle: "Γίνετε μέλος της ομάδας μας" },
    checkout: { title: "Ταμείο", backToOrder: "Πίσω στην παραγγελία", yourDetails: "Τα στοιχεία σας", nameLabel: "Όνομα *", phoneLabelReq: "Τηλέφωνο *", emailLabel: "Email", notesLabel: "Σημειώσεις παραγγελίας", notesPlaceholder: "π.χ. χωρίς καυτερό, επιπλέον σάλτσα…", pickupOrDelivery: "Παραλαβή ή παράδοση", pickup: "🏪 Παραλαβή", delivery: "🛵 Παράδοση (+2,00 €)", streetPlaceholder: "Οδός και αριθμός", zipPlaceholder: "ΤΚ", cityPlaceholder: "Πόλη", payment: "Πληρωμή", continueBtn: "Συνέχεια στην πληρωμή", editDetails: "Επεξεργασία στοιχείων", securePayment: "Ασφαλής πληρωμή", orderSummary: "Παραγγελία", subtotal: "Υποσύνολο", deliveryFee: "Χρέωση παράδοσης", total: "Σύνολο", sslNote: "Κρυπτογραφημένη πληρωμή SSL", thankYou: "Ευχαριστούμε πολύ!", thankYouMsg: "Η παραγγελία σας υποβλήθηκε επιτυχώς", thankYouPhone: "Θα καλέσουμε για επιβεβαίωση.", backHome: "Επιστροφή στην αρχική", cartEmpty: "Το καλάθι σας είναι άδειο.", cartEmptyLink: "Πίσω στην παραγγελία", loading: "Φόρτωση…" },
    footer: { tagline: "Αυθεντική ασιατική κουζίνα στο Schwäbisch Gmünd.", rights: "Με επιφύλαξη παντός δικαιώματος." },
  },

  hi: {
    langName: "हिंदी", flag: "🇮🇳", dir: "ltr",
    nav: { home: "होम", menu: "मेनू", order: "ऑर्डर करें", about: "हमारे बारे में", contact: "संपर्क", careers: "करियर" },
    common: { orderNow: "अभी ऑर्डर करें", viewMenu: "मेनू देखें", viewFullMenu: "पूरा मेनू", learnMore: "और जानें", phone: "फ़ोन", address: "पता", openingHours: "खुलने का समय", closed: "बंद", monday: "सोमवार", saturday: "शनिवार", sunday: "रविवार" },
    home: { heroDesc: "प्रामाणिक एशियाई व्यंजन — कुरकुरे स्प्रिंग रोल्स से लेकर फ्राइड राइस और सुगंधित थाई करी तक। रोज़ ताज़ा तैयार, प्यार से परोसा जाता है।", categoriesTitle: "हमें क्या खास बनाता है", noodleBox: "नूडल बॉक्स", noodleBoxDesc: "फ्राइड नूडल्स या राइस, रोज़ ताज़ा", curry: "थाई करी", curryDesc: "मलाईदार नारियल दूध, ताज़ी जड़ी-बूटियाँ", springRolls: "स्प्रिंग रोल्स", springRollsDesc: "कुरकुरे तले हुए, घर की चटनी", freshTitle: "ताज़ी सामग्री, रोज़ तैयार", freshDesc: "हम रोज़ ताज़ी सब्जियाँ, उच्च गुणवत्ता वाला मांस और चुनी हुई मसाले इस्तेमाल करते हैं — गुणवत्ता में कोई समझौता नहीं।", testimonialsTitle: "हमारे मेहमान क्या कहते हैं", testimonialQuote: "\"Schwäbisch Gmünd का सबसे अच्छा एशियाई रेस्तरां! नूडल बॉक्स बेमिसाल है।\"", testimonialAuthor: "— Maria S., वफ़ादार ग्राहक", ctaTitle: "एशियाई खाने की इच्छा हो रही है?", ctaDesc: "अभी ऑनलाइन ऑर्डर करें या Ledergasse 44–46 पर आएँ।", ctaBtn: "ऑनलाइन ऑर्डर करें" },
    menu: { title: "मेनू", subtitle: "रोज़ ताज़ा तैयार।" },
    order: { title: "ऑर्डर करें", subtitle: "अपने व्यंजन चुनें और हम पुष्टि के लिए फ़ोन करेंगे।", phoneDirect: "सीधे कॉल करें:", cartTitle: "कार्ट", cartEmpty: "कार्ट खाली है", cartEmptyHint: "व्यंजन चुनें", total: "कुल", checkout: "चेकआउट", phoneAlt: "फ़ोन पर ऑर्डर करना पसंद करेंगे?", small: "छोटा", large: "बड़ा", addToCart: "जोड़ें", sauceNote: "शामिल सॉस: सोया, मीठा-खट्टा, या नारियल दूध के साथ थाई करी" },
    about: { title: "हमारे बारे में", subtitle: "Schwäbisch Gmünd के दिल में प्रामाणिक एशियाई व्यंजन।", storyTag: "हमारी कहानी", whoTag: "हम कौन हैं", whoTitle: "स्वाद के प्रति जुनून", whoDesc: "LYS Noodle Box दिल से प्रामाणिक एशियाई व्यंजन प्रस्तुत करता है।", drivesTag: "हमारी प्रेरणा", drivesTitle: "हमारी प्रेरणा", valueHeart: "दिल से", valueHeartDesc: "हर व्यंजन सच्चे जुनून और देखभाल के साथ तैयार किया जाता है — फास्ट फूड नहीं, असली खाना।", valueFresh: "ताज़ी सामग्री", valueFreshDesc: "हम रोज़ ताज़ी, उच्च गुणवत्ता वाली सामग्री इस्तेमाल करते हैं — बिना समझौते के।", valueFamily: "पारिवारिक", valueFamilyDesc: "पारिवारिक व्यवसाय होने के नाते, गर्मजोशी और आतिथ्य सबसे पहले।", valueLocal: "स्थानीय जड़ें", valueLocalDesc: "Schwäbisch Gmünd के दिल में — एशियाई विशेषताओं के लिए आपका पड़ोसी।", hoursTag: "हमेशा आपके लिए", hoursTitle: "खुलने का समय", addressTag: "हमें खोजें", addressTitle: "पता", mondayFriday: "सोमवार – शुक्रवार", saturdayHours: "शनिवार", sundayClosed: "बंद" },
    contact: { title: "संपर्क", subtitle: "हमें लिखें", reachTitle: "हमसे कैसे संपर्क करें", phoneLabel: "फ़ोन", phoneHint: "सबसे तेज़ तरीका फ़ोन है", addressLabel: "पता", hoursLabel: "खुलने का समय", hoursMoSa: "सोम–शनि: 11:00–20:30", hoursSun: "रविवार बंद", mapsBtn: "Google Maps में खोलें", msgTitle: "संदेश भेजें", thankYouTitle: "आपके संदेश के लिए धन्यवाद!", thankYouDesc: "हम जल्द से जल्द आपसे संपर्क करेंगे।", nameLabel: "नाम", namePlaceholder: "राम शर्मा", emailLabel: "ईमेल", emailPlaceholder: "आपका@email.in", msgLabel: "संदेश", msgPlaceholder: "हम आपकी कैसे मदद कर सकते हैं?", sendBtn: "संदेश भेजें" },
    careers: { title: "करियर", subtitle: "हमारी टीम से जुड़ें" },
    checkout: { title: "चेकआउट", backToOrder: "ऑर्डर पर वापस", yourDetails: "आपकी जानकारी", nameLabel: "नाम *", phoneLabelReq: "फ़ोन *", emailLabel: "ईमेल", notesLabel: "ऑर्डर नोट्स", notesPlaceholder: "जैसे: बिना मिर्च, अतिरिक्त सॉस…", pickupOrDelivery: "पिकअप या डिलीवरी", pickup: "🏪 पिकअप", delivery: "🛵 डिलीवरी (+2,00 €)", streetPlaceholder: "सड़क और नंबर", zipPlaceholder: "पिन कोड", cityPlaceholder: "शहर", payment: "भुगतान", continueBtn: "भुगतान जारी रखें", editDetails: "जानकारी संपादित करें", securePayment: "सुरक्षित भुगतान", orderSummary: "ऑर्डर", subtotal: "उप-योग", deliveryFee: "डिलीवरी शुल्क", total: "कुल", sslNote: "SSL-एन्क्रिप्टेड भुगतान", thankYou: "बहुत-बहुत धन्यवाद!", thankYouMsg: "आपका ऑर्डर सफलतापूर्वक दिया गया", thankYouPhone: "पुष्टि के लिए हम फ़ोन करेंगे।", backHome: "होमपेज पर वापस", cartEmpty: "आपका कार्ट खाली है।", cartEmptyLink: "ऑर्डर पर वापस", loading: "लोड हो रहा है…" },
    footer: { tagline: "Schwäbisch Gmünd में प्रामाणिक एशियाई व्यंजन।", rights: "सर्वाधिकार सुरक्षित।" },
  },

  uk: {
    langName: "Українська", flag: "🇺🇦", dir: "ltr",
    nav: { home: "Головна", menu: "Меню", order: "Замовити", about: "Про нас", contact: "Контакти", careers: "Вакансії" },
    common: { orderNow: "Замовити зараз", viewMenu: "Переглянути меню", viewFullMenu: "Повне меню", learnMore: "Дізнатися більше", phone: "Телефон", address: "Адреса", openingHours: "Години роботи", closed: "Зачинено", monday: "Понеділок", saturday: "Субота", sunday: "Неділя" },
    home: { heroDesc: "Справжня азійська кухня — від хрустких спрінг-ролів і смаженого рису до ароматних тайських каррі. Щодня свіжо приготовлено, подано з любов'ю.", categoriesTitle: "Що робить нас особливими", noodleBox: "Noodle Box", noodleBoxDesc: "Смажена локшина або рис, щодня свіжий", curry: "Тайське каррі", curryDesc: "Вершкове кокосове молоко, свіжі трави", springRolls: "Спрінг-роли", springRollsDesc: "Хрустко обсмажені, домашній соус", freshTitle: "Свіжі інгредієнти, приготовані щодня", freshDesc: "Щодня ми використовуємо свіжі овочі, якісне м'ясо та відібрані спеції — без компромісів.", testimonialsTitle: "Відгуки наших гостей", testimonialQuote: "\"Найкращий азійський ресторан у Швебіш-Гмюнді! Noodle Box просто неперевершений.\"", testimonialAuthor: "— Maria S., постійний клієнт", ctaTitle: "Захотілося азійської їжі?", ctaDesc: "Замовляйте онлайн або завітайте до нас на Ledergasse 44–46.", ctaBtn: "Замовити онлайн" },
    menu: { title: "Меню", subtitle: "Щодня свіжо приготовлено." },
    order: { title: "Замовити", subtitle: "Оберіть страви, і ми зателефонуємо для підтвердження.", phoneDirect: "Зателефонувати напряму:", cartTitle: "Кошик", cartEmpty: "Кошик порожній", cartEmptyHint: "Оберіть страви", total: "Разом", checkout: "До каси", phoneAlt: "Бажаєте замовити по телефону?", small: "Малий", large: "Великий", addToCart: "Додати", sauceNote: "Включає соус: соєвий, кисло-солодкий або тайське каррі з кокосовим молоком" },
    about: { title: "Про нас", subtitle: "Справжня азійська кухня в серці Швебіш-Гмюнда.", storyTag: "Наша історія", whoTag: "Хто ми", whoTitle: "Пристрасть до смаку", whoDesc: "LYS Noodle Box — це справжня азійська кухня від серця.", drivesTag: "Що нас надихає", drivesTitle: "Що нас надихає", valueHeart: "Від серця", valueHeartDesc: "Кожна страва готується з щирою пристрастю — не фастфуд, а справжня кухня.", valueFresh: "Свіжі інгредієнти", valueFreshDesc: "Щодня використовуємо свіжі, якісні інгредієнти — без компромісів.", valueFamily: "Сімейний бізнес", valueFamilyDesc: "Як сімейний бізнес, тепло і гостинність — на першому місці.", valueLocal: "Місцеве коріння", valueLocalDesc: "У серці Швебіш-Гмюнда — ваш сусід для азійських спеціалітетів.", hoursTag: "Завжди для вас", hoursTitle: "Години роботи", addressTag: "Знайдіть нас", addressTitle: "Адреса", mondayFriday: "Понеділок – П'ятниця", saturdayHours: "Субота", sundayClosed: "Зачинено" },
    contact: { title: "Контакти", subtitle: "Напишіть нам", reachTitle: "Як з нами зв'язатися", phoneLabel: "Телефон", phoneHint: "Найшвидший спосіб — зателефонувати", addressLabel: "Адреса", hoursLabel: "Години роботи", hoursMoSa: "Пн–Сб: 11:00–20:30", hoursSun: "Неділя зачинено", mapsBtn: "Відкрити в Google Maps", msgTitle: "Надіслати повідомлення", thankYouTitle: "Дякуємо за повідомлення!", thankYouDesc: "Ми зв'яжемося з вами якнайшвидше.", nameLabel: "Ім'я", namePlaceholder: "Іван Петренко", emailLabel: "Ел. пошта", emailPlaceholder: "ваш@email.ua", msgLabel: "Повідомлення", msgPlaceholder: "Чим ми можемо вам допомогти?", sendBtn: "Надіслати" },
    careers: { title: "Вакансії", subtitle: "Приєднуйтесь до нашої команди" },
    checkout: { title: "Каса", backToOrder: "Назад до замовлення", yourDetails: "Ваші дані", nameLabel: "Ім'я *", phoneLabelReq: "Телефон *", emailLabel: "Ел. пошта", notesLabel: "Примітки до замовлення", notesPlaceholder: "напр. без гостроти, додатковий соус…", pickupOrDelivery: "Самовивіз або доставка", pickup: "🏪 Самовивіз", delivery: "🛵 Доставка (+2,00 €)", streetPlaceholder: "Вулиця і номер будинку", zipPlaceholder: "Поштовий індекс", cityPlaceholder: "Місто", payment: "Оплата", continueBtn: "Перейти до оплати", editDetails: "Редагувати дані", securePayment: "Безпечна оплата", orderSummary: "Замовлення", subtotal: "Проміжний підсумок", deliveryFee: "Вартість доставки", total: "Разом", sslNote: "SSL-шифрування", thankYou: "Велике дякую!", thankYouMsg: "Ваше замовлення успішно оформлено", thankYouPhone: "Ми зателефонуємо для підтвердження.", backHome: "На головну", cartEmpty: "Ваш кошик порожній.", cartEmptyLink: "Назад до замовлення", loading: "Завантаження…" },
    footer: { tagline: "Справжня азійська кухня у Швебіш-Гмюнді.", rights: "Усі права захищено." },
  },
};

export const languages = Object.entries(t).map(([code, trans]) => ({
  code: code as LangCode,
  name: trans.langName,
  flag: trans.flag,
  dir: trans.dir,
}));

export default t;
